// Entity Explorer contract QA. Run with index.html?qa=ee.
(function () {
  "use strict";
  if (!/[?&]qa=ee/.test(location.search)) return;
  var sleep = function (ms) { return new Promise(function (r) { setTimeout(r, ms); }); }, J = JSON.stringify;
  var ok = function (c, m) { if (!c) throw new Error(m || "assertion failed"); }, host = document.createElement("div"); host.style.cssText = "position:absolute;left:-10000px;top:0"; document.body.appendChild(host);
  function frame(src) { return new Promise(function (res) { var f = document.createElement("iframe"); f.style.cssText = "width:1300px;height:900px;border:0"; f.onload = function () { var w = f.contentWindow; w.__errs = []; w.addEventListener("error", function (e) { w.__errs.push(e.message); }); setTimeout(function () { res({ f: f, w: w, d: w.document, B: w.BVC }); }, 140); }; f.src = src; host.appendChild(f); }); }
  function load(hash) { return frame("index.html?eechild=" + Math.random().toString(36).slice(2) + (hash || "#gen-22:2")); }
  function variant(code, hash) { return fetch("index.html").then(function (r) { return r.text(); }).then(function (h) { h = h.replace("<head>", '<head><base href="' + location.origin + '/">').replace('<script src="data/projection.research.js"></script>', '<script src="data/projection.research.js"></script><script>' + code + "</script>"); return new Promise(function (res) { var f = document.createElement("iframe"); f.style.cssText = "width:1300px;height:900px;border:0"; f.onload = function () { var w = f.contentWindow; w.__errs = []; w.addEventListener("error", function (e) { w.__errs.push(e.message); }); setTimeout(function () { res({ f: f, w: w, d: w.document, B: w.BVC }); }, 180); }; f.srcdoc = h; host.appendChild(f); }); }); }
  function clean(x) { x.f.remove(); }
  function qa(x, s) { return [].slice.call(x.d.querySelectorAll(s)); }
  function click(x, s) { var e = typeof s === "string" ? x.d.querySelector(s) : s; ok(e, "missing " + s); e.dispatchEvent(new x.w.MouseEvent("click", { bubbles: true, cancelable: true })); return e; }
  function change(x, id, v) { var e = x.d.getElementById(id); e.value = v; e.dispatchEvent(new x.w.Event("change", { bubbles: true })); }
  function open(x) { x.B.openSearch(""); return sleep(80); }
  function ids(x) { return qa(x, "#search-results [data-entity-id]").map(function (e) { return e.dataset.entityId; }); }
  var personCode = 'window.BVC_PROJECTION.persons={"JBC-CR-PERSON-TEST-001":{stable_id:"JBC-CR-PERSON-TEST-001",legacy_key:"test_person",type:"person",display_label:"아브라함",aliases:["Test Abraham"],status:"APPROVED",authority:{project:"qa"},source_refs:[{id:"QA"}],reader:{headline:"명시적 Person projection"},role:"시험 인물",period:"족장 시대",period_sort_value:100,region:{canonical:"가나안"},passage_refs:["gen-12:1"],connected:{events:[{event_id:"EV-1",label:"명시적 사건"}]}}};';
  var placeCode = 'window.BVC_PROJECTION.places["JBC-CR-PLACE-NEW-001"]={stable_id:"JBC-CR-PLACE-NEW-001",legacy_key:"new_place",type:"place",display_label:"새 장소",aliases:[],status:"APPROVED",authority:{project:"qa"},source_refs:[{id:"QA"}],reader:{headline:"새 projection 장소"},location:{reader_status:"UNKNOWN",sentences:[]},region:{canonical:"시험 지역"},passage_refs:["rev-1:1"],media:[]};';
  var T = [], t = function (id, name, fn) { T.push({ id: id, name: name, fn: fn }); };

  t("EE-01", "empty search opens all entity explorer", async function () { var x = await load(); await open(x); ok(ids(x).length === x.B.store.list().length && ids(x).length > 0); clean(x); });
  t("EE-02", "explorer records come from shared store only", async function () { var x = await load(); await open(x); var a = ids(x).sort(), b = x.B.store.list().map(function (e) { return e.stable_id; }).sort(); ok(a.join() === b.join()); clean(x); });
  t("EE-03", "no manual entity catalog", async function () { var x = await load(); ok(!qa(x, 'script[src*="catalog"],script[src*="people-list"],script[src*="places-list"]').length); clean(x); });
  t("EE-04", "Person and Place share one store contract", async function () { var x = await load(), a = x.B.store.list(); ok(a.some(function (e) { return e.entity_type === "Person"; }) && a.some(function (e) { return e.entity_type === "Place"; }) && a.every(function (e) { return e.stable_id && e.display_label && e.provenance.origin; })); clean(x); });
  t("EE-05", "CARD and LIST have identical stable ids", async function () { var x = await load(); await open(x); var a = ids(x); click(x, '[data-swfilter="view:list"]'); var b = ids(x); ok(a.join() === b.join()); clean(x); });
  t("EE-06", "query filters current entity set", async function () { var x = await load(); x.B.openSearch("브엘세바"); await sleep(80); var a = ids(x); ok(a.length === 1 && a[0] === "JBC-CR-PLACE-BEERSHEBA-001"); clean(x); });
  t("EE-07", "type filters Person Place All", async function () { var x = await load(); await open(x); click(x, '[data-swfilter="type:person"]'); ok(qa(x, "[data-entity-id] .ee-primary").every(function (e) { return e.dataset.kind === "p"; })); click(x, '[data-swfilter="type:place"]'); ok(qa(x, "[data-entity-id] .ee-primary").every(function (e) { return e.dataset.kind === "l"; })); click(x, '[data-swfilter="type:all"]'); ok(ids(x).length === x.B.store.list().length); clean(x); });
  t("EE-08", "testament uses explicit or validated refs", async function () { var x = await load(); await open(x); click(x, '[data-swfilter="testament:ot"]'); var a = ids(x); ok(a.indexOf("JBC-CR-PLACE-BEERSHEBA-001") >= 0 && a.indexOf("JBC-CR-PLACE-GERAR-001") >= 0 && a.indexOf("abraham") < 0); click(x, '[data-swfilter="testament:nt"]'); ok(ids(x).length === 0); clean(x); });
  t("EE-09", "period options generated from current records", async function () { var x = await variant(personCode); await open(x); ok(qa(x, "#sw-period option").map(function (o) { return o.value; }).indexOf("족장 시대") >= 0); clean(x); });
  t("EE-10", "region options generated from current records", async function () { var x = await load(); await open(x); var v = qa(x, "#sw-region option").map(function (o) { return o.value; }); ok(v.indexOf("Beersheba Valley / northern Negev") >= 0 && v.indexOf("Southern Canaan / northwestern Negev–Gaza hinterland") >= 0); clean(x); });
  t("EE-11", "Korean label sort deterministic", async function () { var x = await load(); var a = x.B.entityExplorer.set("", { sort: "label" }).map(function (e) { return e.display_label; }), b = x.B.entityExplorer.set("", { sort: "label" }).map(function (e) { return e.display_label; }); ok(a.join() === b.join() && a.join() === a.slice().sort(function (u, v) { return u.localeCompare(v, "ko"); }).join()); clean(x); });
  t("EE-12", "Bible order uses earliest explicit passage", async function () { var x = await load(), a = x.B.entityExplorer.set("", { sort: "bible" }); ok(a.filter(function (e) { return e.passage_refs.length; })[0].stable_id === "JBC-CR-PLACE-GERAR-001"); clean(x); });
  t("EE-13", "period sort leaves missing metadata last", async function () { var x = await variant(personCode), a = x.B.entityExplorer.set("", { sort: "period" }); ok(a[0].stable_id === "JBC-CR-PERSON-TEST-001" && a[a.length - 1].period_sort_value == null); clean(x); });
  t("EE-14", "verified representative image may render", async function () { var x = await load(); await open(x); ok(x.d.querySelector('[data-entity-id="JBC-CR-PLACE-BEERSHEBA-001"] img.ee-thumb')); clean(x); });
  t("EE-15", "missing or failed media renders without placeholder image", async function () { var x = await load(); await open(x); ok(!x.d.querySelector('[data-entity-id="moriah"] img')); var im = x.d.querySelector('[data-entity-id="JBC-CR-PLACE-BEERSHEBA-001"] img.ee-thumb'); ok(im); im.dispatchEvent(new x.w.Event("error")); ok(!x.d.querySelector('[data-entity-id="JBC-CR-PLACE-BEERSHEBA-001"] img.ee-thumb')); clean(x); });
  t("EE-16", "selection resolves the same stable id", async function () { var x = await load(); await open(x); click(x, '[data-entity-id="JBC-CR-PLACE-BEERSHEBA-001"] .ee-primary'); await sleep(80); ok(x.B.stableId(x.B.state.entity.kind, x.B.state.entity.id) === "JBC-CR-PLACE-BEERSHEBA-001"); clean(x); });
  t("EE-17", "selection opens existing Detail", async function () { var x = await load(); await open(x); click(x, '[data-entity-id="JBC-CR-PLACE-GERAR-001"] .ee-primary'); await sleep(80); ok(x.d.querySelector('#panel .detail[data-stable-id="JBC-CR-PLACE-GERAR-001"]')); clean(x); });
  t("EE-18", "selection preserves current passage", async function () { var x = await load("#gen-22:2"); await open(x); click(x, '[data-entity-id="JBC-CR-PLACE-GERAR-001"] .ee-primary'); await sleep(80); ok(x.B.state.passage === "gen-22"); clean(x); });
  t("EE-19", "selection preserves verse and anchor", async function () { var x = await load("#gen-22:12"); var a = x.B.scrollAnchor(); await open(x); click(x, '[data-entity-id="JBC-CR-PLACE-BEERSHEBA-001"] .ee-primary'); await sleep(100); var b = x.B.scrollAnchor(); ok(x.B.state.verse === 12 && a && b && a.verse === b.verse); clean(x); });
  t("EE-20", "Place Scripture and map actions honor explicit metadata and controlled degradation", async function () { var x = await load(); await open(x); click(x, '[data-entity-id="JBC-CR-PLACE-GERAR-001"] [data-ee-action="scripture"]'); await sleep(100); ok(x.B.state.passage === "gen-10" && x.B.state.entity.id === "gerar", "earliest explicit passage"); await open(x); click(x, '[data-entity-id="JBC-CR-PLACE-BEERSHEBA-001"] [data-ee-action="map"]'); await sleep(100); ok(x.B.state.view === "map" && x.B.state.entity.id === "beersheba" && !x.d.querySelector('#map-body .pin[data-id="beersheba"]')); clean(x); });
  t("EE-21", "Person event action only for explicit relations", async function () { var x = await variant(personCode); await open(x); ok(!x.d.querySelector('[data-entity-id="abraham"] [data-ee-action="events"]') && x.d.querySelector('[data-entity-id="JBC-CR-PERSON-TEST-001"] [data-ee-action="events"]')); clean(x); });
  t("EE-22", "new projection entity appears automatically", async function () { var x = await variant(placeCode); await open(x); ok(x.d.querySelector('[data-entity-id="JBC-CR-PLACE-NEW-001"]') && x.B.store.get("JBC-CR-PLACE-NEW-001")); clean(x); });
  t("EE-23", "duplicate name never merges stable ids", async function () { var x = await variant(personCode); var same = x.B.store.list().filter(function (e) { return e.display_label === "아브라함"; }); ok(same.length === 2 && same[0].stable_id !== same[1].stable_id); clean(x); });
  t("EE-24", "reference and Scripture search preserved", async function () { var x = await load(); x.B.openSearch("요 3:16"); await sleep(80); ok(x.d.querySelector('[data-search][data-kind="r"]')); var q = x.d.getElementById("sw-query"); q.value = "독생자"; q.dispatchEvent(new x.w.Event("input", { bubbles: true })); await sleep(80); ok(x.d.querySelector('[data-search][data-kind="v"][data-id="jhn-3:16"]')); clean(x); });
  t("EE-25", "existing Search Workspace QA remains installed", async function () { var x = await load(); ok(x.d.querySelector('script[src="qa-sw.js"]')); clean(x); });
  t("EE-26", "existing Detail Map Scripture APIs remain available", async function () { var x = await load(); ok(x.B.detailContext && x.B.geo && x.B.openRelatedPassage && x.B.store.indexAt); clean(x); });
  t("EE-27", "zero new console errors", async function () { var x = await variant(personCode + placeCode); await open(x); click(x, '[data-swfilter="view:list"]'); ok(x.w.__errs.length === 0, x.w.__errs.join(" | ")); clean(x); });

  // ---- regression: the header search INPUT (real click / focus / typing), not only the openSearch() API ----
  var SID = "JBC-CR-PLACE-BEERSHEBA-001";
  function realClick(x, id) { var e = x.d.getElementById(id); ok(e, "missing #" + id); e.focus(); e.dispatchEvent(new x.w.MouseEvent("click", { bubbles: true, cancelable: true })); return e; }
  t("EE-28", "clicking the header search input opens the Explorer with every Person/Place and no error", async function () {
    var x = await load(); var h0 = x.w.location.hash; realClick(x, "search"); await sleep(200); var S = x.B.searchState;
    ok(S.open === true && !x.d.getElementById("search-workspace").hidden && x.d.body.dataset.search === "open", "search workspace is open after one click");
    ok(ids(x).length === x.B.store.list().length && ids(x).length > 0, "empty query shows the whole current projection dataset: " + ids(x).length + "/" + x.B.store.list().length);
    ok(x.B.state.entity === null && !/undefined/.test(x.w.location.hash) && x.w.location.hash.split("&")[0] === h0.split("&")[0], "no entity was selected by the click itself; hash clean: " + x.w.location.hash);
    ok(x.d.activeElement && x.d.activeElement.id === "sw-query", "focus moved to the workspace query"); ok(x.w.__errs.length === 0, x.w.__errs.join(" | ")); clean(x);
  });
  t("EE-29", "an open search screen is not treated as a result row (body[data-search] must not hijack clicks)", async function () {
    var x = await load(); realClick(x, "search"); await sleep(120); ok(x.B.searchState.open, "open"); realClick(x, "sw-query"); await sleep(60); realClick(x, "search"); await sleep(60); click(x, '[data-swfilter="view:list"]'); await sleep(60);
    ok(x.B.searchState.open && x.B.state.entity === null && !/undefined/.test(x.w.location.hash), "clicks inside the open search screen keep it open and select nothing"); ok(ids(x).length === x.B.store.list().length, "same dataset in LIST view"); ok(x.w.__errs.length === 0, x.w.__errs.join(" | ")); clean(x);
  });
  t("EE-30", "typing filters the same dataset immediately; clearing restores everything", async function () {
    var x = await load(); realClick(x, "search"); await sleep(100); var all = ids(x), lab = x.B.store.list().filter(function (e) { return e.stable_id === SID; })[0].display_label; var q = x.d.getElementById("sw-query"); q.value = lab; q.dispatchEvent(new x.w.Event("input", { bubbles: true })); await sleep(80);
    var f = ids(x); ok(f.length > 0 && f.length <= all.length && f.indexOf(SID) >= 0 && f.every(function (i) { return all.indexOf(i) >= 0; }), "filtered result is a subset of the same dataset and contains the match: " + f.length + "/" + all.length);
    q.value = ""; q.dispatchEvent(new x.w.Event("input", { bubbles: true })); await sleep(80); ok(ids(x).join() === all.join() && x.B.searchState.open, "clearing the query shows the full dataset again"); ok(x.w.__errs.length === 0, x.w.__errs.join(" | ")); clean(x);
  });
  t("EE-31", "choosing an entity from the input-opened Explorer uses the existing stable_id Detail and keeps the Scripture context", async function () {
    var x = await load("#gen-22:19"); var p0 = x.B.state.passage, v0 = x.B.state.verse; realClick(x, "search"); await sleep(100); var row = x.d.querySelector('#search-results [data-entity-id="' + SID + '"] [data-search="1"]'); ok(row, "Beersheba row present"); click(x, row); await sleep(150);
    ok(x.B.state.entity && x.B.state.entity.id === "beersheba" && x.B.stableId("l", "beersheba") === SID, "entity selected by its stable_id"); var d = x.d.querySelector("#panel .detail"); ok(d && d.dataset.stableId === SID, "the existing Detail shows that stable_id");
    ok(x.B.state.passage === p0 && x.B.state.verse === v0 && !x.B.searchState.open && x.d.body.dataset.search === undefined, "Scripture passage/verse kept; the search screen closed"); ok(x.w.__errs.length === 0, x.w.__errs.join(" | ")); clean(x);
  });
  t("EE-32", "the other entry points (toolbar button, rail, slash key) still open the same Explorer", async function () {
    var x = await load(); click(x, "#search-open"); await sleep(80); ok(x.B.searchState.open && ids(x).length === x.B.store.list().length, "#search-open"); x.B.closeSearch(false); await sleep(40);
    var r = x.d.getElementById("rail-search"); if (r) { click(x, r); await sleep(80); ok(x.B.searchState.open, "rail search"); x.B.closeSearch(false); await sleep(40); }
    x.d.body.dispatchEvent(new x.w.KeyboardEvent("keydown", { key: "/", bubbles: true, cancelable: true })); await sleep(80); ok(x.B.searchState.open && x.B.state.entity === null, "slash key"); ok(x.w.__errs.length === 0, x.w.__errs.join(" | ")); clean(x);
  });

  (async function () { var res = []; for (var c of T) { var pass = true, err = ""; try { await Promise.race([c.fn(), new Promise(function (_, reject) { setTimeout(function () { reject(new Error("TIMEOUT 40s")); }, 40000); })]); } catch (e) { pass = false; err = e.message; } res.push({ id: c.id, name: c.name, pass: pass, err: err }); } var p = res.filter(function (r) { return r.pass; }).length; window.BVC_EE_QA = { pass: p, total: res.length, results: res }; var el = document.createElement("div"); el.id = "ee-qa-report"; el.className = "qa"; document.body.appendChild(el); el.textContent = "ENTITY_EXPLORER_QA " + p + "/" + res.length + (p === res.length ? " PASS" : " FAIL") + "\n" + res.map(function (r) { return (r.pass ? "PASS " : "FAIL ") + r.id + " " + r.name + (r.err ? "\n   ✗ " + r.err : ""); }).join("\n"); })();
})();
