// Entity Explorer CURRENT contract QA. Run with ?qa=ee
// Supersedes the pre-2026-10-05 Explorer suite tied to removed #search/type-filter/dialog layouts.
(function(){
"use strict";if(!/[?&]qa=ee/.test(location.search))return;
var sleep=ms=>new Promise(r=>setTimeout(r,ms)),ok=(c,m)=>{if(!c)throw new Error(m||"assertion failed")};
var host=document.createElement("div");host.style.cssText="position:absolute;left:-20000px;top:0";document.body.appendChild(host);
function frame(hash,code,w,h){return new Promise(function(res,rej){var f=document.createElement("iframe");f.style.cssText="width:"+(w||1440)+"px;height:"+(h||900)+"px;border:0";f.onload=function(){setTimeout(function(){res({f:f,w:f.contentWindow,d:f.contentDocument,B:f.contentWindow.BVC})},220)};host.appendChild(f);if(!code){f.src="index.html?eechild="+Math.random().toString(36).slice(2)+(hash||"#gen-22:19");return;}fetch("index.html").then(r=>r.text()).then(function(html){html=html.replace("<head>",'<head><base href="'+location.origin+'/">').replace('<script src="data/projection.research.js"></script>','<script src="data/projection.research.js"></script><script>'+code+"<\/script>");f.srcdoc=html;}).catch(rej)})}
function clean(x){try{x.f.remove()}catch(e){}}
function ids(x){return [...x.d.querySelectorAll("#search-results [data-entity-id]")].map(e=>e.dataset.entityId)}
function click(x,s){var e=typeof s==="string"?x.d.querySelector(s):s;ok(e,"missing "+s);e.dispatchEvent(new x.w.MouseEvent("click",{bubbles:true,cancelable:true}));return e}
function modeExpected(B,mode){return B.entityExplorer.set("",{type:mode}).map(e=>e.stable_id)}
function open(x,q){x.B.openSearch(q||"");return sleep(80)}
function detailSid(x){var d=x.d.querySelector("#panel .detail,[data-detail][data-stable-id]");return d&&d.dataset.stableId}
function row(x,sid){return x.d.querySelector('#search-results [data-entity-id="'+sid+'"]')}
function rowButton(x,sid){var r=row(x,sid);return r&&(r.querySelector("[data-search],.ee-primary,button")||r)}
function visible(el,w){if(!el)return false;var cs=w.getComputedStyle(el),r=el.getBoundingClientRect();return !el.hidden&&cs.display!=="none"&&cs.visibility!=="hidden"&&r.width>0&&r.height>0}
var GERAR="JBC-CR-PLACE-GERAR-001",BS="JBC-CR-PLACE-BEERSHEBA-001",EV="JBC-CR-EVENT-GERAR-ABRAHAM-SARAH-01";
var T=[],t=(id,name,fn)=>T.push({id,name,fn});

t("EE-01","current Explorer workspace contract is installed",async ev=>{var x=await frame("#gen-22:19");ok(x.B&&x.B.openSearch&&x.B.entityExplorer&&x.B.store,"BVC Explorer API");["place","person","event","route"].forEach(m=>ok(x.d.querySelector('[data-swmode="'+m+'"]'),"mode "+m));ok(x.d.querySelector("#sw-query")&&x.d.querySelector("#search-results")&&x.d.querySelector("#sw-sort"),"current controls");ok(!x.d.querySelector("#search"),"removed legacy #search must not return");ev.push("current workspace selectors present");clean(x)});

t("EE-02","opening Explore preserves Scripture context and enters explore perspective",async ev=>{var x=await frame("#gen-22:19"),p=x.B.state.passage,v=x.B.state.verse;await open(x);ok(x.B.state.view==="explore"&&x.d.body.dataset.view==="explore","explore perspective");ok(x.B.state.passage===p&&x.B.state.verse===v,"Scripture context changed");ok(!x.d.querySelector("#search-workspace").hidden,"workspace hidden");ev.push(p+":"+v);clean(x)});

t("EE-03","default Place mode renders exactly the current visible Place/Region set",async ev=>{var x=await frame("#gen-22:19");await open(x);var a=ids(x),b=modeExpected(x.B,"place");ok(a.join()===b.join(),"actual="+a+" expected="+b);ok(a.indexOf(BS)>=0&&a.indexOf(GERAR)>=0,"reference fixtures missing");ev.push("place results="+a.length);clean(x)});

t("EE-04","mode tabs are visibility-gated by current professional data",async ev=>{var x=await frame("#gen-22:19");await open(x);var visibleTypes=x.B.store.list().map(e=>e.entity_type),has={place:visibleTypes.some(t=>t==="Place"||t==="Region"),person:visibleTypes.includes("Person"),event:visibleTypes.includes("Event"),route:visibleTypes.includes("Route")};for(var m of Object.keys(has)){var b=x.d.querySelector('[data-swmode="'+m+'"]');ok(b.hidden===!has[m],m+" hidden="+b.hidden+" expected="+(!has[m]))}ev.push(JSON.stringify(has));clean(x)});

t("EE-05","query filters only the active mode and keeps stable identities",async ev=>{var x=await frame("#gen-22:19");x.B.openSearch("브엘세바");await sleep(80);var a=ids(x);ok(a.length===1&&a[0]===BS,"query results "+a);ok(row(x,BS),"stable-id row missing");ev.push("브엘세바 → "+BS);clean(x)});

t("EE-06","Card/List views preserve the same stable-id result set",async ev=>{var x=await frame("#gen-22:19");await open(x);var a=ids(x).slice();click(x,'[data-swfilter="view:list"]');await sleep(40);var b=ids(x);ok(a.join()===b.join(),"CARD/LIST mismatch");ok(x.B.searchState.view==="list","state not list");ev.push("results="+b.length);clean(x)});

t("EE-07","sort controls operate on the current entity set without identity loss",async ev=>{var x=await frame("#gen-22:19");await open(x);var base=ids(x).slice().sort(),s=x.d.querySelector("#sw-sort");s.value="bible";s.dispatchEvent(new x.w.Event("change",{bubbles:true}));await sleep(50);ok(ids(x).slice().sort().join()===base.join(),"bible sort changed set");s.value="label";s.dispatchEvent(new x.w.Event("change",{bubbles:true}));await sleep(50);ok(ids(x).slice().sort().join()===base.join(),"label sort changed set");ev.push("sort identity invariant");clean(x)});

t("EE-08","clicking a result selects the same stable_id, keeps Explore open, and opens Detail",async ev=>{var x=await frame("#gen-22:19");await open(x);var b=rowButton(x,GERAR);ok(b,"Gerar row button");click(x,b);await sleep(100);ok(x.B.state.view==="explore"&&x.B.searchState.open,"Explorer closed");ok(x.B.state.entity&&x.B.stableId(x.B.state.entity.kind,x.B.state.entity.id)===GERAR,"selected identity");ok(detailSid(x)===GERAR,"Detail stable id "+detailSid(x));ev.push("Explorer → Detail "+GERAR);clean(x)});

t("EE-09","entity selection does not move the Scripture passage or verse",async ev=>{var x=await frame("#gen-22:19"),p=x.B.state.passage,v=x.B.state.verse;await open(x);click(x,rowButton(x,BS));await sleep(100);ok(x.B.state.passage===p&&x.B.state.verse===v,"context changed");ev.push(p+":"+v+" retained");clean(x)});

t("EE-10","successive result clicks replace Detail only and keep current Explore query",async ev=>{var x=await frame("#gen-22:19");await open(x);var q=x.d.querySelector("#sw-query");q.value="";q.dispatchEvent(new x.w.Event("input",{bubbles:true}));var set=x.d.querySelector("#search-results");click(x,rowButton(x,BS));await sleep(80);ok(detailSid(x)===BS,"BS detail");click(x,rowButton(x,GERAR));await sleep(80);ok(detailSid(x)===GERAR,"Gerar detail");ok(x.B.state.view==="explore"&&x.d.querySelector("#search-results")===set,"workspace replaced");ev.push("Detail replacement PASS");clean(x)});

t("EE-11","Gerar Research layer exposes only exact-bound internal Event/Route research objects",async ev=>{var x=await frame("#gen-20:1");x.B.entityExplorer.select(GERAR);await sleep(80);var d=x.d.querySelector("#panel details.research");ok(d,"research details");d.open=true;var links=[...d.querySelectorAll("[data-related-entity]")].map(b=>b.dataset.relatedEntity),events=links.filter(s=>/^JBC-CR-EVENT-GERAR-/.test(s));ok(events.length===6,"events="+events.length);ok(links.every(s=>/^JBC-CR-EVENT-GERAR-/.test(s)||/^JBC-CR-ROUTE-/.test(s)),"unexpected internal relation");ev.push("exact internal events=6");clean(x)});

t("EE-12","direct internal Event selection uses Event Detail, not Place Detail",async ev=>{var x=await frame("#gen-20:1");ok(x.B.entityExplorer.select(EV),"select event");await sleep(80);var a=x.d.querySelector('#panel article[data-detail="evt"][data-stable-id="'+EV+'"]');ok(a,"Event detail");ok(/내부 연구 객체|비공개/.test(a.textContent),"boundary missing");ok(!a.querySelector("[data-map-focus-place]"),"Place map action leaked");ev.push("Event Detail boundary PASS");clean(x)});

t("EE-13","unpublished Event remains absent from reader-facing Explore and quick search",async ev=>{var x=await frame("#gen-20:1");ok(x.B.readerVisible(EV)===false,"Event visibility gate");await open(x);ok(!row(x,EV),"Event leaked into Explore");ok(!x.B.quickSearchItems("Abraham_and_Sarah").some(r=>r.sid===EV),"Event leaked into quick search");ev.push("reader gate PASS");clean(x)});

t("EE-14","Event Explore mode becomes available automatically after publication authority exists",async ev=>{var code='var r=window.BVC_PROJECTION.events&&window.BVC_PROJECTION.events["'+EV+'"];if(r){r.reader.published=true;r.activation.publishable=true;}';var x=await frame("#gen-20:1",code);await open(x);var tab=x.d.querySelector('[data-swmode="event"]');ok(tab&&!tab.hidden,"Event mode hidden");click(x,tab);await sleep(70);ok(x.B.searchState.mode==="event","mode state");ok(ids(x).indexOf(EV)>=0,"published Event missing");ev.push("future publication path PASS");clean(x)});

t("EE-15","deep Study action hands the selected stable identity back to Study",async ev=>{var x=await frame("#gen-22:19");await open(x);click(x,rowButton(x,BS));await sleep(80);var deep=x.d.querySelector('[data-deep-study="'+BS+'"]');ok(deep,"deep Study action");click(x,deep);await sleep(110);ok(x.B.state.view==="study","not study");ok(x.B.state.entity&&x.B.stableId(x.B.state.entity.kind,x.B.state.entity.id)===BS,"identity lost");ok(x.d.querySelector("#search-workspace").hidden,"Explore still visible");ev.push("Explore → Study handoff PASS");clean(x)});

t("EE-16","Discovery result cards keep reader-first presentation and no duplicate action footer",async ev=>{var x=await frame("#gen-22:19");await open(x);var b=row(x,BS),g=row(x,GERAR);ok(b&&g,"fixture cards");ok(!x.d.querySelector("#search-results .ee-actions,#search-results [data-ee-action]"),"duplicate action footer");ok(!/\b(DISPUTED|VERIFY|HOLD)\b/.test((b.textContent||"")+" "+(g.textContent||"")),"raw research state leaked");ev.push("reader-first cards PASS");clean(x)});

t("EE-17","stable identity remains common across Explorer row, Detail and Store",async ev=>{var x=await frame("#gen-22:19");await open(x);var r=row(x,BS);ok(r&&r.dataset.entityId===BS,"row sid");click(x,rowButton(x,BS));await sleep(80);ok(detailSid(x)===BS,"detail sid");ok(x.B.store.get(BS)&&x.B.store.get(BS).stable_id===BS,"store sid");ev.push(BS);clean(x)});

t("EE-18","current Explorer run introduces no uncaught browser error",async ev=>{var x=await frame("#gen-22:19");var errs=[];x.w.addEventListener("error",e=>errs.push(e.message));await open(x);click(x,'[data-swfilter="view:list"]');await sleep(40);click(x,rowButton(x,GERAR));await sleep(70);ok(!errs.length,errs.join(" | "));ev.push("errors=0");clean(x)});

(async()=>{var res=[];for(var c of T){var evidence=[],pass=true,err="";try{await Promise.race([c.fn(evidence),new Promise((_,rej)=>setTimeout(()=>rej(new Error("TIMEOUT 20s")),20000))])}catch(e){pass=false;err=e&&e.message||String(e)}res.push({id:c.id,name:c.name,pass,err,evidence})}var p=res.filter(r=>r.pass).length;window.BVC_EE_QA={contract:"ENTITY_EXPLORER_CURRENT_20261005",pass:p,total:res.length,verdict:p===res.length?"PASS":"FAIL",results:res};var pre=document.createElement("pre");pre.id="ee-qa-report";pre.hidden=true;pre.textContent=JSON.stringify(window.BVC_EE_QA,null,2);document.body.appendChild(pre)})();
})();