// Bible World Navigation QA (Wide Exploration Board + Topic panel). Run with ?qa=jn
(function(){"use strict";if(!/[?&]qa=jn/.test(location.search))return;
var sleep=ms=>new Promise(r=>setTimeout(r,ms)),ok=(c,m)=>{if(!c)throw Error(m)},R=[],$=s=>document.querySelector(s),$$=s=>[].slice.call(document.querySelectorAll(s));
async function t(id,name,fn){var pass=true,err="",ev=[];try{await fn(ev)}catch(e){pass=false;err=e.message}R.push({id,name,pass,err,evidence:ev})}
function snap(){var c=BVC.ui.gcam;return{passage:BVC.state.passage,verse:BVC.state.verse,view:BVC.state.view,cam:c?[+c.x.toFixed(2),+c.y.toFixed(2),+c.w.toFixed(2)].join(","):"default",routes:$$("#map-body .gm-route-inferred").map(e=>e.dataset.routeLabel),layers:[BVC.ui.mapDisplay.terrain,BVC.ui.mapDisplay.hydrology,BVC.ui.mapDisplay.routes].join()}}
async function openTopic(cat,id){$("[data-nav-board-open]").click();await sleep(30);$('[data-nav-tab="'+cat+'"]').click();await sleep(20);var c=$('[data-nav-topic="'+id+'"]');ok(c,"card "+id);c.click();await sleep(250);if(BVC.mapRenderer&&BVC.mapRenderer.mode()==="maplibre"){for(var i=0;i<40&&BVC.mapRenderer.map()&&BVC.mapRenderer.map().isMoving();i++)await sleep(100)}}
async function reset(){document.getElementById("brand-home").click();await sleep(80)}
(async()=>{
await sleep(300);
await t("JN-01","IDLE: context + open button + timeline link only; layers only in Map Settings",async ev=>{BVC.go("gen-26");await sleep(60);var g=$("#guide-pane");ok(g.dataset.navState==="idle","not idle");ok(/주제 탐색하기/.test(g.textContent)&&/현재/.test(g.textContent),"open/current");ok(!$$("#guide-pane [data-jnav-book]").length&&!/성경책|성경 공간|자연환경|성경 사건/.test(g.textContent),"legacy accordion/book list leaked");ok($("[data-jnav-timeline]"),"timeline link");ok(!$$("#guide-pane [data-map-layer]").length&&!/지도 레이어/.test(g.textContent),"layer controls must live only in Map Settings");var grp=$$("#map-settings-pop [data-set-group] .set-h").map(x=>x.textContent).join("/");ok(grp==="지명/자연·지형/이동·경로/지도 배경","settings groups: "+grp);var ks=$$("#map-settings-pop [data-map-layer]").map(x=>x.dataset.mapLayer).join();ok(ks==="labels,ancientRef,modernNames,hydrology,terrain,routes,legend","layer keys: "+ks);ok(!$("[data-map-layer=externalRef],[data-map-layer=allLabels]"),"external/all-labels options must be gone");ok($("#topic-board").hidden,"board should start closed");ev.push("idle hub, no book list")});
await t("JN-02","Board: four production tabs, planned era cards and working presets",async ev=>{$("[data-nav-board-open]").click();await sleep(40);ok(!$("#topic-board").hidden,"board closed");var tabs=$$("#topic-board [role=tab]").map(x=>x.textContent).join("/");ok(tabs==="시대 지도/인물·여정/주제 오버레이/기초 지리·자연환경","tabs: "+tabs);ok($$("#topic-board .tb-card").length>0,"no cards");ok($$("#topic-board .tb-card.is-planned").length>0,"planned era cards missing");$('[data-nav-tab="journey"]').click();await sleep(20);ok($$("#topic-board [data-nav-topic]").length>=5,"working journey cards missing");document.dispatchEvent(new KeyboardEvent("keydown",{key:"Escape",bubbles:true}));await sleep(20);ok($("#topic-board").hidden,"Esc should close board");ev.push(tabs)});
await t("JN-03","Topic card applies map preset immediately and closes board",async ev=>{await reset();BVC.go("exo-3");await sleep(60);var before=snap();await openTopic("reference","geo.south-canaan");var a=snap();ok($("#topic-board").hidden,"board still open");ok($("#guide-pane").dataset.navState==="topic-active","not topic-active");ok(a.cam!==before.cam&&a.cam.split(",")[2]==="5.6","camera not on south-canaan preset: "+a.cam);ok(a.routes.length===0,"geography preset must not draw routes");ev.push(before.cam+" -> "+a.cam)});
await t("JN-04","Steps 1→2→3 change map state; only current step expanded",async ev=>{await reset();await openTopic("journey","ot.isaac-gerar-beersheba");var s=[snap()];for(var i=0;i<3;i++){ok($$("#guide-pane [data-part=current-step]").length===1,"exactly one expanded step");ok($$("#guide-pane [aria-current=step]").length===1,"one current step");$("#guide-next").click();await sleep(250);s.push(snap())}ok(new Set(s.map(x=>x.verse)).size===4,"verse did not move per step: "+s.map(x=>x.verse));ok(new Set(s.map(x=>x.cam)).size>=2,"camera never changed: "+s.map(x=>x.cam));ok(s[2].routes.join()==="Abimelech_delegation_Gerar_to_Beersheba","step 3 approved route not shown: "+s[2].routes);ok(s[1].routes.every(r=>r!=="Abimelech_delegation_Gerar_to_Beersheba")&&s[3].routes.length===0,"routes leaked across steps");$("#guide-prev").click();await sleep(200);ok(BVC.ui.nav.step===2,"prev failed");$('[data-nav-step="0"]').click();await sleep(200);ok(BVC.ui.nav.step===0&&BVC.state.verse===1,"step title click did not switch map/passage");ev.push(s.map(x=>x.verse+"@"+x.cam).join(" | "))});
await t("JN-05","Passage links, Scripture Research and Timeline reuse existing destinations",async ev=>{await reset();await openTopic("journey","ot.moriah-beersheba");var st=$('#guide-pane [data-nav-step="1"]');ok(st&&/22:19/.test(st.textContent),"scene 2 passage reference on the rail");st.click();await sleep(250);ok(BVC.state.passage==="gen-22"&&BVC.state.verse===19&&BVC.ui.nav.topic==="ot.moriah-beersheba"&&BVC.ui.nav.step===1,"scene selection broke topic/passage/verse: "+BVC.state.passage+":"+BVC.state.verse);$('[data-nav-act="research"]').click();await sleep(200);ok(BVC.state.view==="study"&&BVC.state.panel==="open"&&BVC.state.tab==="context"&&/본문연구/.test($(".pane-title").textContent),"research did not open existing Scripture Research");$('[data-nav-act="timeline"]').click();await sleep(200);ok(BVC.state.view==="timeline"&&!$("#timeline-pane").hidden&&BVC.state.passage==="gen-22","timeline link did not open existing Timeline at step passage");$("#rail-study").click();await sleep(100);ok(BVC.state.view==="study","could not return");ev.push("passage/research/timeline ok")});
await t("JN-06","Authority: inferred route dotted, no route without approved geometry",async ev=>{await reset();await openTopic("journey","ot.isaac-gerar-beersheba");$("#guide-next").click();await sleep(150);$("#guide-next").click();await sleep(250);var rt=$$("#map-body .gm-route-inferred");ok(rt.length===1,"expected one inferred route");ok(rt.every(e=>e.getAttribute("data-route-mode")==="PRESENTATION_ONLY_INFERRED_ROUTE"&&/\d/.test(getComputedStyle(e).strokeDasharray)),"inferred route must be dotted/dashed");ok(!$$("#map-body polyline:not(.gm-route-inferred)").length,"unexpected solid route polyline");ok($("#guide-pane .jn-card [data-part=uncertainty]"),"uncertainty note missing");ok($$("#map-body g.gm").some(g=>/\?$/.test(g.textContent.trim())),"inferred place must carry ?");await reset();await openTopic("journey","nt.athens-corinth");$("#guide-next").click();await sleep(250);ok(!$$("#map-body .gm-route-inferred").length,"unresolved/unknown route must not be drawn");ev.push("dotted ok, unknown not drawn")});
await t("JN-07","Unpublished research entities never surface in Navigation",async ev=>{await reset();$("[data-nav-board-open]").click();await sleep(30);var txt="";["era","journey","theme","reference"].forEach(c=>{$('[data-nav-tab="'+c+'"]').click();txt+=$("#topic-board").textContent});await openTopic("journey","nt.macedonia-achaia");txt+=$("#guide-pane").textContent;ok(!/JBC-CR-|ACHAIA|AMALEK|아가야 지역|아말렉/.test(txt.replace(/마게도냐와 아가야/g,"").replace(/아가야로/g,"")),"unpublished entity leaked: "+txt.slice(0,80));ev.push("no unpublished ids/names")});
await t("JN-08","Ending or leaving a topic keeps user map settings (scene presets never overwrite them) and returns to IDLE",async ev=>{await reset();var base=JSON.stringify(BVC.ui.mapDisplay);await openTopic("reference","nature.waters");ok(JSON.stringify(BVC.ui.mapDisplay)===base,"scene preset overwrote user map settings");$("[data-nav-end]").click();await sleep(120);ok($("#guide-pane").dataset.navState==="idle"&&JSON.stringify(BVC.ui.mapDisplay)===base,"settings changed on end");await openTopic("era","era.patriarchal");BVC.go("exo-3");await sleep(120);ok($("#guide-pane").dataset.navState==="idle"&&BVC.ui.navRouteIds===null,"top navigation should leave topic");ok(JSON.stringify(BVC.ui.mapDisplay)===base,"settings changed on leave");ev.push("unchanged")});
await t("JN-09","Stable identity preserved: topic place keeps the existing entity identity; navigation never auto-selects or opens Detail; explicit place selection opens the existing entity",async ev=>{await reset();BVC.go("gen-26");await sleep(60);BVC.state.entity=null;await openTopic("journey","ot.gerar-abraham");var sid=BVC.stableId("l","gerar");ok(sid,"stable id lost");var m=$('#map-body g.gm[data-place="gerar"]');ok(m&&m.dataset.stableId===sid,"topic place marker not bound to the existing gerar stable id");ok(!BVC.state.entity,"navigation must not auto-select a research entity: "+JSON.stringify(BVC.state.entity));ok(BVC.state.panel==="collapsed","Detail must not be forced open");m.dispatchEvent(new MouseEvent("click",{bubbles:true}));await sleep(400);var e=BVC.state.entity;ok(e&&e.kind==="l"&&e.id==="gerar","explicit place selection is not the existing gerar entity: "+JSON.stringify(e));ok(BVC.ui.nav.topic==="ot.gerar-abraham","topic lost on place selection");ev.push("gerar "+sid)});
await t("JN-10","PERSIST: user map settings survive era/track/scene/place/camera changes and are stored locally; only reset restores defaults",async ev=>{await reset();var KEY="jbc.mapPrefs.v1";
var pick=function(sel,v){var el=$(sel);ok(el,"control "+sel);el.value=v;el.dispatchEvent(new Event("change",{bubbles:true}))};
var flip=function(k,want){var el=$('[data-map-layer="'+k+'"]');ok(el,"checkbox "+k);if(el.checked!==want)el.click()};
flip("modernNames",false);flip("terrain",false);flip("hydrology",true);pick('[data-map-pref="modernOpacity"]',"strong");pick('[data-map-pref="modernDetail"]',"few");pick('[data-map-pref="routeStyle"]',"emphasis");await sleep(60);
var want=JSON.stringify(BVC.ui.mapDisplay),stored=localStorage.getItem(KEY);ok(stored===want,"not stored locally: "+stored);ok(BVC.ui.mapDisplay.modernNames===false&&BVC.ui.mapDisplay.terrain===false&&BVC.ui.mapDisplay.routeStyle==="emphasis","UI change not applied");
var same=function(where){ok(JSON.stringify(BVC.ui.mapDisplay)===want,"settings changed after "+where+": "+JSON.stringify(BVC.ui.mapDisplay));var sv=$("#map-body svg.gmap");if(sv)ok(sv.dataset.routeStyle==="emphasis"&&sv.dataset.modernOpacity==="strong","svg lost style after "+where);ok(!$('[data-map-layer="terrain"]').checked&&!$('[data-map-layer="modernNames"]').checked,"panel out of sync after "+where);ok(!$$("#map-body .gm-ref-modern").length,"modern labels reappeared after "+where)};
await openTopic("era","era.patriarchal");var c0=snap().cam;same("era open");$("#guide-next").click();await sleep(250);same("scene next");$("#guide-next").click();await sleep(250);same("scene next 2");
var tr=$('[data-nav-track="isaac"]');if(tr){tr.click();await sleep(250);same("track change")}var c1=snap().cam;ok(c1!==c0,"camera should move with scenes: "+c0+" -> "+c1);
var ra=$('[data-nav-act="research"]');if(ra){ra.click();await sleep(150);same("research open")}
await openTopic("reference","nature.relief");same("reference preset (terrain/hydrology preset ignored)");await openTopic("reference","geo.egypt");same("region move to Egypt");
$("[data-nav-end]").click();await sleep(120);same("topic end");BVC.go("exo-3");await sleep(120);same("passage jump");var z=$('[data-map-action="zoom-in"]');if(z){z.click();await sleep(60);same("manual zoom")}await reset();same("brand home");
ok(localStorage.getItem(KEY)===want,"stored copy drifted");
$('[data-map-action="reset-prefs"]').click();await sleep(80);ok(BVC.ui.mapDisplay.modernNames===true&&BVC.ui.mapDisplay.terrain===true&&BVC.ui.mapDisplay.routeStyle==="standard"&&BVC.ui.mapDisplay.modernOpacity==="normal"&&BVC.ui.mapDisplay.modernDetail==="normal","reset did not restore defaults");ok(localStorage.getItem(KEY)===null,"reset left stored prefs");ok($('[data-map-pref="routeStyle"]').value==="standard"&&$('[data-map-layer="terrain"]').checked,"panel not synced after reset");ev.push(c0+" -> "+c1+" · prefs held")});
await t("JN-11","SHARED journey runtime: Abraham and Paul use the same panel, rail, waypoints and route styles; rail number = map waypoint; thin routes; prefs untouched",async ev=>{await reset();var want=JSON.stringify(BVC.ui.mapDisplay);
for(var spec of [["era","era.patriarchal"],["journey","nt.paul-macedonia-achaia"]]){await openTopic(spec[0],spec[1]);var pane=$("#guide-pane");ok(pane.querySelector("[data-part=journey-navigator]"),spec[1]+": shared navigator");var rail=$$("#guide-pane .jn-step"),cur=$$("#guide-pane .jn-step.is-current");ok(rail.length>=5&&cur.length===1,"rail with exactly one selected scene");
ok(!/HOLD|VERIFY|canonical|projection|identity/i.test(pane.innerText),"no internal status language in navigator");
$("#guide-next").click();await sleep(300);var n=+$("#guide-pane .jn-step.is-current").dataset.wp;var act=$('#map-body .gm-wp-active[data-nav-wp]');ok(act&&+act.dataset.navWp===n,"active waypoint "+n+" matches rail number");
var wid=$$("#map-body .gm-ovroute-active .gm-ovroute-line").map(e=>parseFloat(getComputedStyle(e).strokeWidth));ok(wid.length===1&&wid[0]>=4&&wid[0]<=5,"active route 4–5px: "+wid);
var cw=$$("#map-body .gm-ovroute-context .gm-ovroute-line").map(e=>parseFloat(getComputedStyle(e).strokeWidth));ok(cw.every(v=>v>=2.5&&v<=3.5),"context routes 2.5–3.5px: "+cw.join());
ok($$("#map-body .gm-ovroute-arrow, #map-body .gm-ovroute-head").length<=12,"sparse arrows");
ok($("#map-body .jn-legend"),"compact legend");ok(document.querySelector(".mp-title").textContent.indexOf("성경 여정 지도 |")===0,"top-left context chip");
ok(pane.querySelectorAll('[data-nav-act="timeline"]').length===1&&pane.querySelector(".jn-erag [data-nav-act=timeline]"),"연표보기 once, next to the era label");
var rb=pane.querySelector('.jn-card [data-nav-act="research"]');ok(rb&&rb.getAttribute("aria-pressed")==="false"&&BVC.state.panel==="collapsed","본문연구 on the scene card; research closed by default");
var mw0=document.getElementById("map-pane").getBoundingClientRect().width;rb.click();await sleep(500);ok(BVC.state.panel==="open"&&$('.jn-card [data-nav-act="research"]').getAttribute("aria-pressed")==="true","one click opens research");
$('.jn-card [data-nav-act="research"]').click();await sleep(500);ok(BVC.state.panel==="collapsed"&&$('.jn-card [data-nav-act="research"]').getAttribute("aria-pressed")==="false","second click closes research");
$('.jn-card [data-nav-act="research"]').click();await sleep(400);var sceneBefore=BVC.mapScene().scene;$("#guide-next").click();await sleep(700);ok(BVC.state.panel==="open"&&BVC.mapScene().scene===sceneBefore+1,"CANONICAL: an open research panel stays open and follows the new scene (only an explicit close/collapse closes it)");$('.rs-shell [data-rs-collapse]').click();await sleep(500);ok(BVC.state.panel==="collapsed","explicit collapse closes it");
var sgs=$$("#map-body .gm-ovroute-active[data-route-segment-id]");ok(sgs.length===1,"active route has a segment id");var sg0=sgs[0].dataset;
ok($('#map-body [data-waypoint-id="'+sg0.fromWaypoint+'"]')&&$('#map-body [data-waypoint-id="'+sg0.toWaypoint+'"]')&&$('#guide-pane [data-waypoint-id="'+sg0.toWaypoint+'"]'),"segment from/to waypoint ids exist on map and in rail");
var nn=+$("#guide-pane .jn-step.is-current").dataset.wp,sl=$$("#map-body .gm-seg-label");sl.forEach(g=>{ok(g.dataset.routeSegmentId===sg0.routeSegmentId&&g.dataset.distanceKm&&+g.dataset.toNo===nn&&+g.dataset.fromNo===nn-1&&g.dataset.fromWaypoint&&g.dataset.toWaypoint,"distance label bound to segment "+(nn-1)+"→"+nn)});
var gw=Math.round($("#guide-pane").getBoundingClientRect().width);ok(gw<=310,"narrow right panel: "+gw);
ok(JSON.stringify(BVC.ui.mapDisplay)===want,"prefs unchanged");ev.push(spec[1]+" waypoint "+n+" route "+wid);}
var sc=BVC.mapScene();ok(sc.topic&&sc.waypointNo&&sc.camera,"mapScene snapshot");ok(BVC.ui.mapPrefs===BVC.ui.mapDisplay,"mapPrefs alias");
$("[data-nav-end]").click();await sleep(150);ok(document.body.dataset.journey==="off","layout restored after end")});
await t("JN-12","SHARED PLACE_INDEX: every mapped place is searchable via one PlaceCard; map/search share the key; Gerar/Beersheba open Full Profile; new places get basic cards",async ev=>{await reset();await openTopic("era","era.patriarchal");var idx=BVC.placeIndex(),keys=$$("#map-body [data-nav-place]").map(e=>e.dataset.navPlace);ok(keys.length>=5&&keys.every(k=>idx.byKey[k]),"every mapped place is in the index");
ok(idx.byKey.gerar.hasProfile&&idx.byKey.beersheba.hasProfile&&idx.byKey.gerar.stableId&&!idx.byKey.haran.hasProfile&&!idx.byKey.haran.stableId,"profiles only where they exist");
ok(idx.byKey.haran.passages.length&&idx.byKey.haran.people.length&&idx.byKey.haran.eras.length&&idx.byKey.haran.scenes.length,"aggregated passages/people/eras/scenes");
BVC.openSearch("");await sleep(300);var q=$("#sw-query");q.value="하란";q.dispatchEvent(new Event("input",{bubbles:true}));await sleep(400);var c=$('#search-results .pc-search[data-place-key="haran"]');ok(c,"Haran card in Search");
c.querySelector(".ee-primary").click();await sleep(500);ok($('#panel [data-part="place-basic"]'),"basic detail for place without profile");
q.value="그랄";q.dispatchEvent(new Event("input",{bubbles:true}));await sleep(400);$('#search-results .pc-search[data-place-key="gerar"] .ee-primary').click();await sleep(600);ok(BVC.state.entity&&BVC.state.entity.id==="gerar"&&!$('#panel [data-part="place-basic"]'),"Gerar opens the existing Full Place Profile")});
var p=R.filter(x=>x.pass).length;window.BVC_JN_QA={pass:p,total:R.length,verdict:p===R.length?"PASS":"FAIL",results:R};})();
})();
