// Minimal original-language verse view QA. Run with ?qa=ol  (real UI: CLOSED by default, lazy loading, RTL/LTR, HOLD/ERROR, offset/split, async race)
(function(){"use strict";if(!/[?&]qa=ol/.test(location.search))return;
var sleep=ms=>new Promise(r=>setTimeout(r,ms)),ok=(c,m)=>{if(!c)throw Error(m)},R=[],$=s=>document.querySelector(s),$$=s=>[].slice.call(document.querySelectorAll(s));
async function t(id,name,fn){var pass=true,err="";try{await fn()}catch(e){pass=false;err=e.message}R.push({id:id,name:name,pass:pass,err:err})}
var books=()=>performance.getEntriesByType("resource").map(e=>e.name).filter(n=>/data\/original-language\//.test(n)).map(n=>n.split("/original-language/")[1]);
async function go(ref){var m=/^(.+)-(\d+):(\d+)$/.exec(ref);BVC.go(m[1]+"-"+m[2],+m[3],true);await sleep(120)}
async function until(fn,ms){var t0=Date.now();while(Date.now()-t0<(ms||4000)){if(fn())return true;await sleep(40)}return false}
var tog=()=>$("#ol-toggle"),bodyEl=()=>$("#ol-body"),stt=()=>bodyEl().getAttribute("data-state");
(async()=>{await sleep(500);
await t("OL-01","CLOSED at boot: button present, collapsed, 0 corpus requests",async()=>{ok(tog()&&bodyEl(),"markup");ok(tog().getAttribute("aria-expanded")==="false"&&bodyEl().hidden&&stt()==="CLOSED","not closed");ok(tog().tagName==="BUTTON"&&tog().getAttribute("aria-controls")==="ol-body","a11y attrs");ok(books().length===0,"corpus requests at boot: "+books())});
await t("OL-02","Open with no verse selected: hint only, still 0 corpus requests",async()=>{BVC.go("gen-21");await sleep(150);if(BVC.state.verse!=null){BVC.selectVerse(BVC.state.verse)}await sleep(100);tog().click();await sleep(200);ok(stt()==="OPEN"&&/절을 선택/.test(bodyEl().textContent),"hint "+bodyEl().textContent);ok(books().length===0,"loaded without a verse");tog().click();await sleep(60)});
await t("OL-03","gen-21:14: Hebrew RTL verse; book+dict+reference-map loaded once; close/reopen adds 0",async()=>{await go("gen-21:14");ok(BVC.state.verse===14,"verse 14");var kb=document.querySelector('#verses [data-verse="14"]').textContent;tog().click();ok(await until(()=>stt()==="OPEN"&&$("#ol-body .ol-text")),"no text "+stt());var p=$("#ol-body .ol-text");ok(p.getAttribute("dir")==="rtl"&&p.getAttribute("lang")==="he","rtl/lang");ok(getComputedStyle(p).direction==="rtl","computed direction");ok(/히브리어 · OSHB/.test($("#ol-body .ol-lang").textContent)&&/창세기 21:14/.test($("#ol-body .ol-ref").textContent),"header");ok(/[א-ת]/.test(p.textContent)&&p.textContent.indexOf("/")<0,"hebrew text");var b=books();ok(b.length===3&&b.indexOf("hebrew/gen.js")>=0&&b.indexOf("hebrew/dict.js")>=0&&b.indexOf("reference-map.js")>=0,"requests "+b);ok(document.querySelector('#verses [data-verse="14"]').textContent===kb,"KRV text changed");tog().click();await sleep(60);ok(bodyEl().hidden,"closed");tog().click();await sleep(250);ok(books().length===3,"reopen requested again: "+books())});
await t("OL-04","Same book, other verse: updated with 0 extra requests",async()=>{await go("gen-22:2");ok(await until(()=>/창세기 22:2/.test(bodyEl().textContent)),"not updated "+bodyEl().textContent.slice(0,40));ok(books().length===3,"extra requests "+books());var r1=await BVCOriginalLanguage.getVerse("gen-22:2");ok($("#ol-body .ol-text").textContent.indexOf(r1.verse.t[0][0].replace(/\//g,""))>=0,"text mismatch")});
await t("OL-05","Book switch Genesis -> Exodus loads only Exodus; Matthew switches to Greek (LTR, SBLGNT)",async()=>{await go("exo-3:14");ok(await until(()=>/출애굽기 3:14/.test(bodyEl().textContent)),"exo "+bodyEl().textContent.slice(0,40));var b=books();ok(b.length===4&&b[3]==="hebrew/exo.js","exo load "+b);await go("mat-1:2");ok(await until(()=>/그리스어 · SBLGNT/.test(bodyEl().textContent)),"greek header");var p=$("#ol-body .ol-text");ok(p.getAttribute("dir")==="ltr"&&p.getAttribute("lang")==="grc"&&getComputedStyle(p).direction==="ltr","ltr");ok(/Ἰσαάκ/.test(p.textContent)&&/Ἰσαὰκ/.test(p.textContent)&&!/[⸀-⸅]/.test(p.textContent),"greek text/accents");ok(/마태복음 1:2/.test($("#ol-body .ol-ref").textContent),"ref");var b2=books();ok(b2.length===6&&b2[4]==="greek/mat.js"&&b2[5]==="greek/dict.js","mat load "+b2)});
await t("OL-06","No highlight/marks on source words; tokens are plain buttons (no links/marks/tabindex hacks); no word card open by default",async()=>{ok(!$("#ol-body mark, #ol-body a, #ol-body [tabindex], #ol-body [role=button]"),"highlight/link element present");ok($$("#ol-body .ol-tok").length>=8&&$$("#ol-body .ol-tok").every(b=>b.tagName==="BUTTON"&&b.type==="button"),"token buttons");ok($("#ol-body .ol-card").hidden,"card open by default");ok(!$("#ol-body button:not(.ol-retry):not(.ol-tok):not(.rp-cta)"),"unexpected buttons")});
await t("OL-07","OFFSET deu-29:13 shows source verse 29:12; split/merge num-26:1 shows both sources with review note",async()=>{await go("deu-29:13");ok(await until(()=>/신명기 29:12/.test(bodyEl().textContent)),"offset "+bodyEl().textContent.slice(0,60));ok(/원문 절 번호 기준/.test(bodyEl().textContent),"note");await go("num-26:1");ok(await until(()=>/민수기 25:19/.test(bodyEl().textContent)&&/민수기 26:1/.test(bodyEl().textContent)),"split "+bodyEl().textContent.slice(0,80));ok($$("#ol-body .ol-text").length===2&&/절 경계 검토 중/.test(bodyEl().textContent),"two sources + boundary note")});
await t("OL-08","HOLD (Hebrew psa-72:19, Greek act-19:41): message only, no source text, KRV text kept",async()=>{for(var ref of ["psa-72:19","act-19:41"]){await go(ref);ok(await until(()=>stt()==="HOLD"),ref+" state "+stt());ok(/현재 검토 중/.test(bodyEl().textContent)&&!$("#ol-body .ol-text")&&!/[Ͱ-Ͽ֐-׿ἀ-῿]/.test(bodyEl().textContent),"source guessed for "+ref);var v=BVC.state;ok(document.querySelector('#verses [data-verse="'+v.verse+'"]').textContent.length>5,"KRV verse missing")}});
await t("OL-09","ERROR is isolated and shows the fallback + retry; KRV keeps working",async()=>{var orig=BVCOriginalLanguage.getVerse;BVCOriginalLanguage.getVerse=function(r){return Promise.resolve({status:"ERROR",code:"SCRIPT_LOAD_FAILED",message:"x",krvRef:r})};await go("lev-1:1");ok(await until(()=>stt()==="ERROR"),"state "+stt());ok(/원문을 불러오지 못했습니다/.test(bodyEl().textContent)&&$("#ol-body .ol-retry"),"fallback/retry");ok(document.querySelector('#verses [data-verse="1"]').textContent.length>5,"KRV broken");BVCOriginalLanguage.getVerse=orig;await go("lev-1:2");ok(await until(()=>stt()==="OPEN"),"recovery "+stt())});
await t("OL-10","Async race: a slow earlier request cannot overwrite the current verse",async()=>{var orig=BVCOriginalLanguage.getVerse;BVCOriginalLanguage.getVerse=function(r){var p=orig.call(BVCOriginalLanguage,r);return r==="gen-1:1"?new Promise(res=>setTimeout(()=>p.then(res),700)):p};await go("gen-1:1");await sleep(80);await go("gen-1:2");ok(await until(()=>/창세기 1:2/.test(bodyEl().textContent)),"second not shown");await sleep(900);ok(/창세기 1:2/.test($("#ol-body .ol-head").textContent),"stale overwrote: "+$("#ol-body .ol-head").textContent);BVCOriginalLanguage.getVerse=orig});
await t("OL-11","Escape closes, focus returns to the button; research panel DOM/state untouched",async()=>{var pan=$("#panel").innerHTML.length,st=JSON.stringify({p:BVC.state.passage,v:BVC.state.verse,t:BVC.state.tab});document.dispatchEvent(new KeyboardEvent("keydown",{key:"Escape"}));await sleep(80);ok(bodyEl().hidden&&tog().getAttribute("aria-expanded")==="false","not closed");ok(document.activeElement===tog(),"focus");ok(JSON.stringify({p:BVC.state.passage,v:BVC.state.verse,t:BVC.state.tab})===st&&$("#panel").innerHTML.length===pan,"app state/panel changed")});
await t("OL-12","No lexical/analysis content is shown",async()=>{tog().click();await sleep(300);ok(!/analysis|lemma|morph|N-PRI|Strong/i.test(bodyEl().textContent),"analysis shown");tog().click()});
var krvIn=()=>($("#ol-body .ol-krv-text")||{textContent:""}).textContent,krvOf=n=>document.querySelector('#verses [data-verse="'+n+'"]').textContent.replace(/^\d+/,"").trim(),clickV=n=>document.querySelector('#verses [data-verse="'+n+'"]').click();
await t("OL-13","Paired card: KRV verse + Hebrew source together (gen-21:14), KRV above source",async()=>{await go("gen-21:14");tog().click();ok(await until(()=>stt()==="OPEN"&&$("#ol-body .ol-text")),"open");ok(krvIn()===krvOf(14)&&krvIn().length>5,"krv in card: "+krvIn());ok(/개역한글/.test($("#ol-body .ol-krv-label").textContent)&&/창세기 21:14/.test($("#ol-body .ol-krv-ref").textContent),"krv head");ok(/[א-ת]/.test($("#ol-body .ol-text").textContent),"hebrew");ok($(".ol-krv").compareDocumentPosition($(".ol-src"))&4,"order KRV before source");ok(!$("#ol-body .ol-krv button, #ol-body .ol-krv [tabindex]"),"krv interactive")});
await t("OL-14","Same-book live sync via real verse click: card stays OPEN, KRV+source follow, 0 extra requests",async()=>{var n0=books().length;clickV(15);ok(krvIn()===krvOf(15)&&/21:15/.test($("#ol-body .ol-krv-ref").textContent),"krv not instant: "+krvIn());ok(await until(()=>/창세기 21:15/.test($("#ol-body .ol-src").textContent)&&stt()==="OPEN"),"source not updated");ok(!bodyEl().hidden&&tog().getAttribute("aria-expanded")==="true","closed");var r=await BVCOriginalLanguage.getVerse("gen-21:15");ok($("#ol-body .ol-text").textContent.indexOf(r.verse.t[0][0].replace(/\//g,""))>=0,"source text");ok(books().length===n0,"extra requests")});
await t("OL-15","Cross-book live sync: Exodus loads only Exodus; KRV shown before source is ready",async()=>{var n0=books().length;await go("exo-3:14");ok(krvIn()===krvOf(14)&&/출애굽기 3:14/.test($("#ol-body .ol-krv-ref").textContent),"krv "+krvIn());ok(await until(()=>/출애굽기 3:14/.test($("#ol-body .ol-src").textContent)&&$("#ol-body .ol-text")),"source");var b=books();ok(!bodyEl().hidden&&b.slice(n0).every(x=>/exo/.test(x)),"non-Exodus loads "+b.slice(n0))});
await t("OL-16","OT -> NT live sync: card open, KRV Matthew + Greek SBLGNT LTR",async()=>{await go("mat-1:2");ok(!bodyEl().hidden,"closed");ok(await until(()=>/그리스어 · SBLGNT/.test($("#ol-body .ol-src").textContent)),"greek label");ok(krvIn()===krvOf(2)&&/마태복음 1:2/.test($("#ol-body .ol-krv-ref").textContent),"krv");ok($("#ol-body .ol-text").getAttribute("dir")==="ltr"&&/Ἰσαάκ|Ἰσαὰκ/.test($("#ol-body .ol-text").textContent),"greek");await go("gen-1:3");ok(await until(()=>/히브리어 · OSHB/.test($("#ol-body .ol-src").textContent)),"back to hebrew")});
await t("OL-17","HOLD live transition: new KRV shown, previous source removed, HOLD message",async()=>{await go("gen-21:14");ok(await until(()=>$("#ol-body .ol-text")),"normal");await go("psa-72:19");ok(await until(()=>stt()==="HOLD"),"hold "+stt());ok(!$("#ol-body .ol-text")&&/현재 검토 중/.test($("#ol-body .ol-src").textContent),"source kept/missing msg");ok(krvIn()===krvOf(19)&&/시편 72:19/.test($("#ol-body .ol-krv-ref").textContent),"krv "+krvIn())});
await t("OL-18","ERROR live transition: KRV kept, previous source removed, source-only error",async()=>{await go("gen-21:14");ok(await until(()=>$("#ol-body .ol-text")),"normal");var orig=BVCOriginalLanguage.getVerse;BVCOriginalLanguage.getVerse=function(r){return Promise.resolve({status:"ERROR",code:"SCRIPT_LOAD_FAILED",message:"x",krvRef:r})};await go("gen-21:15");ok(await until(()=>stt()==="ERROR"),"state");ok(!$("#ol-body .ol-text")&&/불러오지 못했습니다/.test($("#ol-body .ol-src").textContent),"source");ok(krvIn()===krvOf(15)&&krvIn().length>5,"krv");BVCOriginalLanguage.getVerse=orig});
await t("OL-19","Race A->B->C: final card is C/C even if A resolves late",async()=>{var orig=BVCOriginalLanguage.getVerse;BVCOriginalLanguage.getVerse=function(r){var p=orig.call(BVCOriginalLanguage,r);return r==="gen-2:1"?new Promise(res=>setTimeout(()=>p.then(res),700)):p};await go("gen-2:1");await go("gen-2:2");await go("gen-2:3");ok(await until(()=>/창세기 2:3/.test($("#ol-body .ol-src").textContent)),"C not shown");await sleep(900);ok(/창세기 2:3/.test($("#ol-body .ol-krv-ref").textContent)&&/창세기 2:3/.test($("#ol-body .ol-src").textContent)&&krvIn()===krvOf(3),"final not C/C");BVCOriginalLanguage.getVerse=orig});
await t("OL-20","Closed card does no work: moving verses adds 0 requests and renders nothing",async()=>{tog().click();await sleep(60);ok(bodyEl().hidden&&!$("#ol-body .ol-krv-text"),"not closed/empty");var n0=books().length;await go("lev-3:1");await go("mat-5:3");await sleep(200);ok(books().length===n0&&!$("#ol-body .ol-krv-text")&&!$("#ol-body .ol-text"),"work while closed")});
await t("OL-21","First verse stays readable: card holds its KRV; card is inline in flow directly under the selected verse",async()=>{for(var ref of ["gen-1:1","mat-1:1"]){await go(ref);if(bodyEl().hidden)tog().click();ok(await until(()=>$("#ol-body .ol-text")),ref+" open");ok(krvIn()===krvOf(1)&&krvIn().length>5,ref+" krv in card");var pv=bodyEl().previousElementSibling;ok(pv&&pv.matches("#verses > .verse")&&pv.dataset.verse==="1"&&getComputedStyle(bodyEl()).position!=="absolute"&&getComputedStyle(bodyEl()).position!=="fixed","card not inline under verse 1: "+ref)}tog().click()});
var WCd=window.BVCOriginalWordCard,cardEl=()=>$("#ol-body .ol-card"),cardTxt=()=>cardEl().textContent,tokBtn=(i,vi)=>$('#ol-body .ol-tok[data-i="'+i+'"][data-vi="'+(vi||0)+'"]');
async function openAt(ref){await go(ref);if(bodyEl().hidden)tog().click();ok(await until(()=>stt()==="OPEN"&&$("#ol-body .ol-tok")),ref+" open")}
var rowOf=k=>{var r=$$("#ol-body .ol-card-row").filter(x=>x.firstChild.textContent===k)[0];return r?r.lastChild.textContent:null};
await t("OL-22","Hebrew Isaac gen-21:3: surface, Korean reading, romanization, VERIFIED headword/basic gloss, POS, audio control",async()=>{await openAt("gen-21:3");var tk=$$("#ol-body .ol-tok").filter(b=>/יִצְחָק/.test(b.textContent.replace(/[֑-ֽ֯]/g,"")))[0];ok(tk,"isaac token");tk.click();ok(!cardEl().hidden&&tk.getAttribute("aria-expanded")==="true","card");ok(/יִצְחָק/.test($("#ol-body .ol-card-surface").textContent)&&$("#ol-body .ol-card-surface").getAttribute("dir")==="rtl","surface");ok(rowOf("한글 발음")==="이츠하크","ko "+rowOf("한글 발음"));ok(rowOf("로마자")==="Yiṣḥāq","la "+rowOf("로마자"));ok(rowOf("표제어")==="יִצְחָק","lemma "+rowOf("표제어"));ok(rowOf("기본 뜻")==="이삭","gloss "+rowOf("기본 뜻"));ok(rowOf("품사")==="고유명사","pos "+rowOf("품사"));var a=$("#ol-body .ol-card-audio");ok(a&&(!a.disabled||/지원하지 않습니다/.test(cardTxt())),"audio control/fallback");ok(!/N-PRI|HNp|\bNp\b|3327 a|어휘 번호 3327/.test(cardTxt()),"raw code shown")});
await t("OL-23","Greek Isaac mat-1:2: Ἰσαάκ / 이사악 / Isaak / lemma / 고유명사",async()=>{await openAt("mat-1:2");var tk=$$("#ol-body .ol-tok").filter(b=>/^Ἰσαάκ/.test(b.textContent))[0];ok(tk,"isaac token");tk.click();ok(/Ἰσαάκ/.test($("#ol-body .ol-card-surface").textContent)&&$("#ol-body .ol-card-surface").getAttribute("dir")==="ltr","surface");ok(rowOf("한글 발음")==="이사악"&&rowOf("로마자")==="Isaak","reading "+rowOf("한글 발음")+"/"+rowOf("로마자"));ok(rowOf("표제어")==="Ἰσαάκ"&&rowOf("품사")==="고유명사","lemma/pos "+rowOf("표제어")+"/"+rowOf("품사"));ok(!/N-PRI/.test(cardTxt()),"raw code")});
await t("OL-24","Ordinary Hebrew (gen-1:1 אֱלֹהִים) uses VERIFIED headword/basic gloss; Greek keeps its existing behavior",async()=>{await openAt("gen-1:1");tokBtn(2).click();ok(/אֱלֹהִים/.test($("#ol-body .ol-card-surface").textContent)&&rowOf("품사")==="명사"&&rowOf("한글 발음").length>=3&&/^ʾ/.test(rowOf("로마자")),"hebrew "+cardTxt());ok(rowOf("표제어")==="אֱלֹהִים"&&rowOf("기본 뜻")==="하나님, 신(들)"&&$("#ol-body .ol-card-row[data-gloss]").getAttribute("data-gloss")==="VERIFIED","verified gloss state");ok(!/이 본문에서의 의미|본문연구 보기/.test(cardTxt()),"unsourced section shown");await openAt("mat-1:2");tokBtn(1).click();ok(rowOf("표제어")==="γεννάω"&&rowOf("품사")==="동사"&&rowOf("한글 발음")==="에겐네센","greek "+cardTxt())});
await t("OL-25","Greek X token (1co-1:4 μου) and U token (jhn-8:5): surface + reading shown, lemma/POS 'analysis pending', nothing guessed",async()=>{for(var q of [["1co-1:4",3],["jhn-8:5",4]]){await openAt(q[0]);tokBtn(q[1]).click();ok(!cardEl().hidden,q[0]+" card");ok(rowOf("한글 발음")&&rowOf("로마자"),q[0]+" reading");ok(rowOf("표제어")==="분석 정보 확인 중"&&rowOf("품사")==="분석 정보 확인 중",q[0]+" analysis row: "+rowOf("표제어")+"/"+rowOf("품사"))}});
await t("OL-26","Verse navigation, Esc order, and closing the source view all close the word card",async()=>{await openAt("gen-21:3");tokBtn(11).click();ok(!cardEl().hidden,"open");await go("gen-21:4");ok(await until(()=>/21:4/.test($("#ol-body .ol-src").textContent)),"moved");ok(cardEl().hidden&&!cardEl().textContent,"card survived verse change");tokBtn(0).click();ok(!cardEl().hidden,"reopen");document.dispatchEvent(new KeyboardEvent("keydown",{key:"Escape"}));await sleep(50);ok(cardEl().hidden&&!bodyEl().hidden,"first Esc must close only the card");ok(document.activeElement===tokBtn(0),"focus returns to token");tokBtn(0).click();tog().click();await sleep(60);ok(bodyEl().hidden&&cardEl().hidden&&!cardEl().textContent,"view close left card");tog().click();await sleep(300);ok(cardEl().hidden,"card dangling after reopen");tog().click()});
await t("OL-27","Keyboard: token buttons are focusable/activatable; card has labelled close; no extra corpus loads from card use",async()=>{tog().click();await sleep(300);var n0=books().length,tk=tokBtn(1);tk.focus();ok(document.activeElement===tk,"focusable");tk.click();ok(!cardEl().hidden&&cardEl().getAttribute("aria-label")&&$("#ol-body .ol-card-x").getAttribute("aria-label")==="단어 카드 닫기","labels");$("#ol-body .ol-card-x").click();ok(cardEl().hidden&&document.activeElement===tk,"close/focus");ok(books().length===n0,"extra requests");tog().click()});
await t("OL-28","Pronunciation (mock speechSynthesis): Hebrew/Greek voice chosen, original token spoken, replay cancels, no-voice fallback",async()=>{var env=WCd.env,o={s:env.synth,u:env.Utter},log=[],voices=[{lang:"en-US"},{lang:"he-IL",name:"H"},{lang:"el-GR",name:"G"}];env.synth=()=>({getVoices:()=>voices,cancel:()=>log.push("cancel"),speak:u=>{log.push("speak:"+u.lang+":"+u.text);setTimeout(()=>u.onstart&&u.onstart(),0)}});var MU=function(t){this.text=t};env.Utter=()=>MU;try{await openAt("gen-1:1");tokBtn(2).click();var a=$("#ol-body .ol-card-audio");ok(!a.disabled,"he enabled");a.click();await sleep(40);ok(log.some(x=>x==="speak:he-IL:"+WCd.describe({lang:"he",tok:["אֱלֹהִ֑ים"],a:null,dict:null}).surface),"he spoken text "+log);ok(!/[\u0591-\u05AF]/.test(log[log.length-1]),"cantillation in playback");a.click();await sleep(40);ok(log.filter(x=>x==="cancel").length>=2,"replay did not cancel "+log);await openAt("mat-1:2");tokBtn(3).click();$("#ol-body .ol-card-audio").click();await sleep(40);ok(log.some(x=>/^speak:el-GR:Ἰσαάκ$/.test(x)),"greek "+log);voices.length=0;await openAt("gen-1:1");tokBtn(2).click();ok($("#ol-body .ol-card-audio").disabled&&/지원하지 않습니다/.test(cardTxt()),"no-voice fallback");ok(!cardEl().hidden&&rowOf("한글 발음"),"card broke without voice");env.synth=()=>null;tokBtn(2).click();tokBtn(2).click();ok($("#ol-body .ol-card-audio").disabled,"no speechSynthesis")}finally{env.synth=o.s;env.Utter=o.u}tog().click()});
await t("OL-29","Conventions: Hebrew/Greek reading rules are deterministic (unit samples)",async()=>{var h=WCd.hebrew,g=WCd.greek;ok(h("חֶסֶד").ko==="헤세드"&&h("חֶסֶד").la==="ḥesed","hesed");ok(h("אַבְרָהָם").ko==="아브라함","abraham");ok(h("יִשְׂרָאֵל").ko==="이스라엘","israel");ok(g("ἀγάπη").ko==="아가페"&&g("ἀγάπη").la==="agapē","agape");ok(g("Ἰησοῦς").la==="Iēsous","iesous");ok(WCd.hebrewPos("HNp")==="고유명사"&&WCd.hebrewPos("HC/Vqw3ms")==="동사"&&WCd.hebrewPos("HNcmsc/Sp3ms")==="명사"&&WCd.hebrewPos("HR/Sp3ms")==="전치사","hebrew pos");ok(WCd.greekPos("N-PRI","noun")==="고유명사"&&WCd.greekPos("T-ASM","det")==="관사"&&WCd.greekPos("X","zzz")===null,"greek pos")});
var p=R.filter(x=>x.pass).length;window.BVC_OLV_QA={pass:p,total:R.length,verdict:p===R.length?"PASS":"FAIL",results:R};
var d=document.createElement("div");d.className="qa";d.id="olv-qa-report";d.style.cssText="white-space:pre;font:12px monospace";d.textContent="OL VERSE VIEW QA "+p+"/"+R.length+" "+window.BVC_OLV_QA.verdict+"\n"+R.map(r=>(r.pass?"PASS ":"FAIL ")+r.id+" "+r.name+(r.err?"\n   "+r.err:"")).join("\n");document.body.appendChild(d);
})();
})();
