// Person-profile routing QA. Run with ?qa=research
(function(){"use strict";if(!/[?&]qa=research/.test(location.search))return;
var sleep=ms=>new Promise(r=>setTimeout(r,ms)),ok=(c,m)=>{if(!c)throw Error(m)},R=[],$=s=>document.querySelector(s),$$=s=>[].slice.call(document.querySelectorAll(s));
async function t(id,name,fn){var pass=true,err="";try{await fn()}catch(e){pass=false;err=e.message}R.push({id,name,pass,err})}
async function until(fn,ms){var t0=Date.now();while(Date.now()-t0<(ms||4000)){if(fn())return true;await sleep(40)}return false}
async function go(ref){var m=/^(.+)-(\d+):(\d+)$/.exec(ref);BVC.go(m[1]+"-"+m[2],+m[3],true);await sleep(180)}
var RP=()=>window.BVCResearchProjection,IDX=()=>window.BVC_RESEARCH_PROJECTION;
(async()=>{await sleep(700);
await t("RP-01","Isaac asset is classified PERSON_PROFILE_WORBS -> PERSON_CARD",async()=>{var d=IDX(),s=d.source;ok(RP()&&RP().ready(),"not ready");ok(s.researchId==="JBC_ISAAC_PERSON_PROFILE_WORBS_20261005_01"&&s.version==="v1.0","identity");ok(s.assetType==="PERSON_PROFILE_WORBS"&&s.entityType==="PERSON"&&s.entityId==="ISAAC"&&s.primaryProjection==="PERSON_CARD","source routing metadata");ok(d.projection.assetType==="PERSON_PROFILE_WORBS"&&d.projection.primary==="PERSON_CARD"&&d.projection.verseWorbsEligible===false,"projection routing metadata")});
await t("RP-02","Research relation locator is preserved without becoming verse WORBS",async()=>{ok(RP().verse("gen-22:1").cls==="DM_PRONOUN_CONTINUATION","22:1 relation");ok(RP().verse("gen-22:2").cls==="DM_NAME","22:2 relation");ok(IDX().counts.DM_NAME===123&&IDX().counts.DM_PRONOUN_CONTINUATION===138&&IDX().counts.STRONGLY_RELATED===69,"counts")});
await t("RP-03","Genesis 22:1 renders registered passage WORBS reader projection, never Isaac profile",async()=>{await go("gen-22:1");var p=$("#panel"),vr=window.BVCVerseResearchProjection;ok(vr&&vr.ready()&&vr.verse("gen-22:1"),"verse provider");ok($('[data-part="verse-worbs"][data-verse-ref="gen-22:1"]'),"verse section");ok($('#panel [data-projection-status="INTERNAL_READER_PROJECTION"]'),"reader projection");ok(/전체 본문 개관/.test(p.textContent)&&/절·단락별 주석/.test(p.textContent)&&/핵심 원어 카드/.test(p.textContent)&&/해석 주의/.test(p.textContent),"reader structure");ok(/נִסָּה/.test(p.textContent)&&/시험하다/.test(p.textContent),"lexical card");ok(!p.querySelector('[data-part="person-card"]')&&!p.querySelector(".rp-summary"),"person profile leaked")});
await t("RP-04","Synthetic registered VERSE_WORBS occupies verse slot without Person Profile substitution",async()=>{var bak=window.BVCVerseResearchProjection;window.BVCVerseResearchProjection={verse:r=>r==="gen-22:1"?{type:"VERSE_WORBS"}:null,render:(box,r)=>{box.hidden=false;box.textContent="SYNTHETIC VERSE WORBS "+r;return Promise.resolve(true)}};try{BVC.render();await sleep(100);ok(/SYNTHETIC VERSE WORBS gen-22:1/.test($("#panel").textContent),"verse provider not routed");ok(!$("#panel .rp-summary")&&!$("#panel [data-part=person-card]"),"person profile substituted")}finally{window.BVCVerseResearchProjection=bak;BVC.render();await sleep(80)}});
await t("RP-05","Clicking Isaac in Scripture opens current canonical Person Card",async()=>{await go("gen-22:2");var n=$("#verses .rp-name");ok(n&&n.textContent==="이삭","Isaac entity link missing");n.click();ok(await until(()=>$('#panel article.detail[data-detail="p"][data-stable-id="JBC_ISAAC_PERSON_PROFILE_WORBS_20261005_01"] [data-person-reader="canonical"]'),4000),"canonical person card did not open");ok($(".pane-title").textContent.trim()==="인물","panel mode");ok(!$("#panel [data-part=person-card]")&&!$("#panel .rp-summary"),"legacy person panel leaked")});
await t("RP-06","Canonical Person Card displays the approved Isaac reader projection",async()=>{var p=$("#panel"),a=$('#panel article.detail[data-detail="p"]');ok(a&&a.dataset.stableId==="JBC_ISAAC_PERSON_PROFILE_WORBS_20261005_01","canonical identity");ok(/이삭은 아브라함과 사라에게 약속된 아들/.test(p.textContent),"summary");ok($('#panel [data-person-reader="canonical"]'),"canonical reader projection")});
await t("RP-07","VERSE -> canonical PERSON -> VERSE transition follows last direct selection",async()=>{BVC.selectVerse(3);await sleep(120);ok($(".pane-title").textContent.trim()==="본문연구","back to verse mode");ok($('[data-part="verse-worbs"][data-verse-ref="gen-22:3"]'),"22:3 verse research slot");ok(!$('#panel article.detail[data-detail="p"]')&&!$("#panel [data-part=person-card]")&&!$("#panel .rp-summary"),"person card persisted")});
await t("RP-08","Related-verse metadata remains available but is link-only",async()=>{var d=IDX();ok(d.projection.relatedVersesRole==="LINK_METADATA_ONLY","role");ok(RP().verse("gen-22:1")&&RP().verse("gen-22:2"),"related refs lost");ok(d.projection.verseWorbsEligible===false,"verse promotion")});
await t("RP-09","Original-language Isaac token CTA targets current canonical Person Card",async()=>{await go("gen-22:2");var tog=$("#ol-toggle");if($("#ol-body").hidden)tog.click();ok(await until(()=>$("#ol-body").getAttribute("data-state")==="OPEN"&&$("#ol-body .ol-tok"),4000),"OL open");var i=+IDX().verses["gen-22:2"].t[0].split("#")[1],b=$$("#ol-body .ol-tok").filter(x=>+x.dataset.i===i)[0];ok(b,"Isaac token");b.click();ok(await until(()=>$("#ol-body .ol-card .rp-cta"),2000),"CTA");var cta=$("#ol-body .ol-card .rp-cta");ok(cta.textContent==="이삭 인물카드 보기"&&cta.dataset.projectionTarget==="PERSON_CARD","wrong CTA");cta.click();ok(await until(()=>$('#panel article.detail[data-detail="p"][data-stable-id="JBC_ISAAC_PERSON_PROFILE_WORBS_20261005_01"] [data-person-reader="canonical"]'),4000),"CTA did not open canonical person card");ok(!$("#panel [data-part=person-card]")&&!$("#panel .rp-summary"),"legacy panel opened");ok(!$("#ol-body .ol-card .rp-panel .rp-summary"),"profile duplicated inline")});
await t("RP-10","Fail closed on routing-metadata mismatch",async()=>{var d=IDX(),old=d.source.primaryProjection;d.source.primaryProjection="VERSE_WORBS";try{ok(!RP().ready()&&RP().verse("gen-22:2")===null,"routing mismatch stayed active")}finally{d.source.primaryProjection=old}ok(RP().ready(),"restore")});
await t("RP-11","Approved research identity and reader content stay unchanged",async()=>{ok(IDX().source.sha256==="e75c9378dab8794728edf4021aecb986cf285ec63818afa067330a059bc2bf66","sha");ok(IDX().source.professionalStatus==="PROFESSIONAL_RESEARCH_PASS"&&IDX().source.representative==="CURRENT_PROJECT01_PROFESSIONAL_REPRESENTATIVE","approval/lineage");var c=await RP().load();ok(c&&c.researchId===IDX().source.researchId&&c.version==="v1.0"&&c.sha256===IDX().source.sha256,"reader identity")});
await t("RP-12","No duplicate storage/projection body in verse locator",async()=>{var raw=JSON.stringify(IDX());ok(raw.indexOf("이삭은 아브라함과 사라에게 약속된 아들")<0,"reader body duplicated into locator");await go("gen-22:1");ok(!$("#panel .rp-summary"),"reader body duplicated into verse panel")});
var p=R.filter(x=>x.pass).length;window.BVC_RP_QA={pass:p,total:R.length,verdict:p===R.length?"PASS":"FAIL",results:R};
var d=document.createElement("div");d.className="qa";d.id="rp-qa-report";d.style.cssText="white-space:pre;font:12px monospace";d.textContent="RESEARCH ROUTING QA "+p+"/"+R.length+" "+window.BVC_RP_QA.verdict+"\n"+R.map(r=>(r.pass?"PASS ":"FAIL ")+r.id+" "+r.name+(r.err?"\n   "+r.err:"")).join("\n");document.body.appendChild(d);
})();
})();