// Shared map/scripture annotation toolbar + multi-verse note scope E2E. Run: ?qa=sa
(function(){
  "use strict";
  if(!/[?&]qa=sa/.test(location.search))return;
  var sleep=ms=>new Promise(r=>setTimeout(r,ms)),ok=(c,m)=>{if(!c)throw new Error(m||"assertion failed")};
  var K="jbc.scripture.annotations.v1", saved={ann:localStorage.getItem(K),notes:localStorage.getItem("bvc.notes.v2"),idx:localStorage.getItem("bvc.noteIndex"),n13:localStorage.getItem("bvc.note.gen-20:1-3"),n1c3:localStorage.getItem("bvc.note.gen-20:1,3")};
  function restore(){if(saved.ann==null)localStorage.removeItem(K);else localStorage.setItem(K,saved.ann);if(saved.notes==null)localStorage.removeItem("bvc.notes.v2");else localStorage.setItem("bvc.notes.v2",saved.notes);if(saved.idx==null)localStorage.removeItem("bvc.noteIndex");else localStorage.setItem("bvc.noteIndex",saved.idx);if(saved.n13==null)localStorage.removeItem("bvc.note.gen-20:1-3");else localStorage.setItem("bvc.note.gen-20:1-3",saved.n13);if(saved.n1c3==null)localStorage.removeItem("bvc.note.gen-20:1,3");else localStorage.setItem("bvc.note.gen-20:1,3",saved.n1c3);}
  function resetSel(){BVC.ui.vsel=[];BVC.ui.vanchor=null;BVC.state.verse=null;BVC.render();}
  function textNode(verse){var v=document.querySelector('#verses .verse[data-verse="'+verse+'"]'),w=document.createTreeWalker(v,NodeFilter.SHOW_TEXT,{acceptNode:n=>n.parentElement?.closest(".vnum")?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT});while(w.nextNode())if(w.currentNode.nodeValue.trim())return w.currentNode;return null}
  function selectText(verse,n){var t=textNode(verse),r=document.createRange();r.setStart(t,0);r.setEnd(t,Math.min(n,t.nodeValue.length));var s=getSelection();s.removeAllRanges();s.addRange(r);document.dispatchEvent(new Event("selectionchange"));return s.toString();}
  function noteScope(){return [...document.querySelectorAll("#panel .scope")].map(e=>e.textContent.trim()).find(x=>x.indexOf("새 메모 대상")===0)||""}
  var T=[],t=(id,name,fn)=>T.push({id,name,fn});
  t("SA-01","contiguous multi-verse selection creates an independent range note",async ev=>{resetSel();BVC.selectVerse(1);BVC.selectVerse(3,"range");ok(JSON.stringify(BVC.ui.vsel)==="[1,2,3]","vsel");ok(/창세기 20장 1–3절/.test(noteScope()),noteScope());document.querySelector("#note-text").value="qa contiguous";document.querySelector("#note-save").click();var a=JSON.parse(localStorage.getItem("bvc.notes.v2")||"[]");ok(a.some(x=>x.text==="qa contiguous"&&JSON.stringify(x.verses)==="[1,2,3]"),"range note record");ev.push(noteScope())});
  t("SA-02","non-contiguous selection creates an independent note and overlap cards",async ev=>{resetSel();BVC.selectVerse(1);BVC.selectVerse(3,"toggle");ok(JSON.stringify(BVC.ui.vsel)==="[1,3]","vsel noncontig");ok(/창세기 20장 1, 3절/.test(noteScope()),noteScope());document.querySelector("#note-text").value="qa noncontiguous";document.querySelector("#note-save").click();resetSel();BVC.selectVerse(2);BVC.setTab("notes");var sums=[...document.querySelectorAll(".note-card summary")].map(x=>x.textContent);ok(sums.some(x=>/1–3절/.test(x)),"overlap note shown for included verse");ev.push(sums.join(" | "))});
  t("SA-03","dragged Scripture text activates shared toolbar Scripture mode",async ev=>{selectText(1,6);await sleep(20);ok(document.body.dataset.annSurface==="scripture","surface");ok(document.querySelector('[data-ann-tool="dist"]').hidden,"distance hidden");ok(document.querySelector('[data-ann-tool="pen"]').getAttribute("aria-label")==="밑줄","pen relabel");var seg=JBC_TEXT_ANN.selectionSegments();ok(seg.length===1&&seg[0].verse===1&&seg[0].start===0&&seg[0].end>0,"segment");ev.push(getSelection().toString())});
  t("SA-04","highlighter stores verse+offset and renders CSS Highlight",async ev=>{document.querySelector('[data-ann-tool="hl"]').click();var x=JBC_TEXT_ANN.state.items.filter(x=>x.passage==="gen-20"&&x.type==="hl");ok(x.length>=1,"stored hl");ok([...CSS.highlights.keys()].some(k=>String(k).indexOf("jbc_hl_")===0),"highlight api");ev.push(JSON.stringify(x[x.length-1]))});
  t("SA-05","underline shares same toolbar and persists as independent annotation",async ev=>{selectText(2,5);await sleep(20);document.querySelector('[data-ann-tool="pen"]').click();var x=JBC_TEXT_ANN.state.items.filter(x=>x.passage==="gen-20"&&x.type==="ul");ok(x.length>=1,"stored ul");ok([...CSS.highlights.keys()].some(k=>String(k).indexOf("jbc_ul_")===0),"underline highlight");ev.push(JSON.stringify(x[x.length-1]))});
  t("SA-06","annotations survive chapter remount",async ev=>{var n=JBC_TEXT_ANN.state.items.filter(x=>x.passage==="gen-20").length;BVC.go("gen-21");BVC.go("gen-20");JBC_TEXT_ANN.render();ok(JBC_TEXT_ANN.state.items.filter(x=>x.passage==="gen-20").length===n,"item persist");ok([...CSS.highlights.keys()].filter(k=>String(k).indexOf("jbc_")===0).length>=2,"render persist");ev.push("items="+n)});
  t("SA-07","Scripture erase + undo works without changing research markup",async ev=>{var before=JBC_TEXT_ANN.state.items.filter(x=>x.passage==="gen-20").length;selectText(1,6);await sleep(20);document.querySelector('[data-ann-tool="eraser"]').click();var after=JBC_TEXT_ANN.state.items.filter(x=>x.passage==="gen-20").length;ok(after<before,"erase");document.querySelector('[data-ann-act="undo"]').click();ok(JBC_TEXT_ANN.state.items.filter(x=>x.passage==="gen-20").length===before,"undo");ok(document.querySelector('#verses .tag'),"entity markup intact");ev.push(before+"→"+after+"→"+before)});
  t("SA-08","returning to map restores map toolbar contract",async ev=>{JBC_TEXT_ANN.activateMap();ok(document.body.dataset.annSurface!=="scripture","map surface");ok(!document.querySelector('[data-ann-tool="dist"]').hidden,"distance visible");ok(document.querySelector('[data-ann-tool="pen"]').getAttribute("aria-label")==="펜","pen restored");ok(document.querySelector("#ann-tools").nextElementSibling===document.querySelector("#quick-search"),"toolbar remains immediately left of quick search");JBC_ANN.setTool("pen");ok(document.querySelector("#ann-layer").dataset.active==="1","map pen active");JBC_ANN.setTool("hand");ev.push("map toolbar restored")});
  (async function(){localStorage.setItem(K,"[]");localStorage.setItem("bvc.notes.v2","[]");JBC_TEXT_ANN.state.items=[];JBC_TEXT_ANN.state.hist=[];JBC_TEXT_ANN.render();var res=[];try{for(var c of T){var ev=[],pass=true,err="";try{await c.fn(ev)}catch(e){pass=false;err=e.message}res.push({id:c.id,name:c.name,pass,err,evidence:ev})}}finally{restore();try{JBC_TEXT_ANN.state.items=JSON.parse(saved.ann||"[]");JBC_TEXT_ANN.state.hist=[];JBC_TEXT_ANN.render()}catch(e){}}
    var p=res.filter(r=>r.pass).length,verdict=p===res.length?"PASS":"FAIL";window.BVC_SA_QA={pass:p,total:res.length,verdict,results:res};var el=document.createElement("pre");el.id="sa-qa-report";el.hidden=true;el.textContent=JSON.stringify(window.BVC_SA_QA,null,2);document.body.appendChild(el);
  })();
})();