"use strict";
// Pipeline tests (node tools/pipeline/test.js): golden counts, provenance of every value, fail-closed negatives,
// Obsidian syntax handling, determinism. Writes tools/pipeline/out/test-results.json (consumed by ?qa=pl).
const fs = require("fs"), os = require("os"), path = require("path"), crypto = require("crypto");
const { run, ingest, discover, loadConfig, loadKrv, SOURCE, GERAR, OVERLAY, ROOT } = require("./run"), { parseNote } = require("./parse"), { normalize } = require("./normalize"), { validate } = require("./validate"), resolver = require("./media-resolver");
const clone = (o) => JSON.parse(JSON.stringify(o)), sha = (f) => crypto.createHash("sha256").update(fs.readFileSync(f)).digest("hex");
const pending = [], results = [], ta = (id, name, fn) => pending.push(Promise.resolve().then(fn).then((ev) => results.push({ id, name, pass: true, evidence: ev || [] }), (e) => results.push({ id, name, pass: false, error: e.message }))), t = (id, name, fn) => { try { const ev = fn() || []; results.push({ id, name, pass: true, evidence: ev }); } catch (e) { results.push({ id, name, pass: false, error: e.message }); } };
const ok = (c, m) => { if (!c) throw new Error(m || "assertion failed"); };

const krv = loadKrv(), overlay = JSON.parse(fs.readFileSync(OVERLAY, "utf8")), dataFile = path.join(ROOT, "data", "projection.research.js"), idxFile = path.join(ROOT, "data", "scripture.index.js");
const base = run({ dryRun: true, krv }), rec = base.norm.record, srcText = fs.readFileSync(SOURCE, "utf8");

t("P01", "parse → validate → normalize on the real Beersheba note passes (35 checks, all passing incl. media contract, preview resolution, spatial read model, approval and identity)", () => { ok(base.validation.ok, JSON.stringify(base.validation.errors)); const failing = base.validation.checks.filter((c) => !c.ok).map((c) => c.id); ok(base.validation.checks.length === 35 && failing.length === 0, "no check may be open: " + failing); return ["checks=" + base.validation.checks.length, "open checks=" + failing.join(), "warnings=" + JSON.stringify(base.validation.warnings)]; });

t("P02", "golden counts from the note", () => {
  const c = { direct: rec.passage_links.filter((l) => l.group === "direct").length, related: rec.passage_links.filter((l) => l.group === "related").length, claims: rec.claims.length, verify: rec.verify.length, hold: rec.hold.length, media: rec.media.length, candidates: rec.candidates.length, quick_facts: rec.reader.quick_facts.length, relations: rec.relations.length };
  ok(c.direct === 6 && c.related === 2 && c.claims === 10 && c.verify === 4 && c.hold === 4 && c.media === 3 && c.candidates === 2 && c.quick_facts === 6 && c.relations === 12, JSON.stringify(c)); ok(!rec.reader.quick_facts.some((r) => r[0] === "중요한 인물"), "hidden row leaked"); return [JSON.stringify(c)];
});

t("P03", "stable_id, status, certainty and VERIFY/HOLD are carried exactly; no coordinate on the biblical place", () => {
  ok(rec.stable_id === "JBC-CR-PLACE-BEERSHEBA-001" && rec.status === "STAGE_APPROVED_WITH_VERIFY" && rec.certainty === "HIGH_FOR_BIBLICAL_IDENTITY" && rec.coordinate_certainty === "DISPUTED_FOR_EXACT_BIBLICAL_POINT", "identity/status");
  ok(rec.coordinates === null && rec.coordinate_status === "NO_EXACT_POINT_ASSIGNED", "primary coordinate"); ok(rec.VERIFY_HOLD.verify && rec.VERIFY_HOLD.hold && rec.verify.map((v) => v.id).join() === "VERIFY-BS-01,VERIFY-BS-02,VERIFY-BS-03,VERIFY-BS-04", "verify ids");
  ok(rec.candidates.every((c) => c.equivalence_locked === false), "candidates equated"); ok(rec.source_refs[0].sha256 === sha(SOURCE), "source hash"); return ["sha256=" + rec.source_refs[0].sha256];
});

t("P04", "every string value in the record is traceable to the note, the app overlay, or a declared derivation", () => {
  const srcPlain = srcText.replace(/`/g, ""), overlayStr = new Set(); (function w(o) { if (typeof o === "string") overlayStr.add(o); else if (o && typeof o === "object") Object.values(o).forEach(w); })(overlay);
  const exempt = /^(spatial\..+|source_refs\.0\.(path|sha256)|source_locator|VERIFY_HOLD\.reason|location\.reader_status|coordinate_status|type|media\.\d+\.attribution|media\.\d+\.provider|media\.\d+\.(rights_note|display_mode|content_hash|preview_url|attribution_derived|declared_rights\..+|resolution\..+|rights\.(status|license_code|clearance_basis\..+)|target_ref\.binding)|relations\.\d+\.(from|to|relation|evidence|certainty)|(relations|connected\.places)\.\d+\.binding\.(state|rule|reason|source_locator|target_id|candidates\.\d+|preserved_last_known_good)|claims\.\d+\.(statement|class|locator|confidence)|passage_links\.\d+\.(group|book)|candidates\.\d+\.(role|note|status)|authority\.registry_effect)$/;
  const miss = []; (function w(o, p) { if (typeof o === "string") { if (!overlayStr.has(o) && !exempt.test(p) && srcText.indexOf(o) < 0 && srcPlain.indexOf(o) < 0) miss.push(p + " = " + o); } else if (Array.isArray(o)) o.forEach((v, i) => w(v, p ? p + "." + i : String(i))); else if (o && typeof o === "object") Object.keys(o).forEach((k) => w(o[k], p ? p + "." + k : k)); })(rec, "");
  ok(!miss.length, "untraceable: " + JSON.stringify(miss));
  const claimsOk = rec.claims.every((c) => srcText.indexOf(c.id) >= 0 && srcText.indexOf(c.locator) >= 0 && srcText.indexOf(c.statement) >= 0); ok(claimsOk, "claim text/locator not in note");
  const mediaOk = rec.media.every((m) => srcText.indexOf(m.creator) >= 0 && srcText.indexOf(m.license) >= 0 && srcText.indexOf(m.file) >= 0); ok(mediaOk, "media metadata not in note"); return ["untraceable=0", "app-overlay fields=" + base.norm.overlayFields.length];
});

t("P05", "no navigation metadata is invented (lock §9): the note has none → navigation is null, warning recorded", () => { ok(rec.navigation === null && base.norm.warnings.some((w) => /navigation metadata/.test(w)), "navigation"); return [base.norm.warnings.join(" | ")]; });
t("P05A", "explicit Place navigation supports multiple approved paths without duplicating the research asset", () => {
  const p = parseNote(SOURCE), k = "NAVIGATION_TEST";
  p.order.push(k); p.sections[k] = { heading: k, yaml: [{ data: { navigation_paths: [
    { domain: "구약 역사", period: "검증 시대 A", story: "검증 이야기 A", scene: "검증 장면 A", passage_refs: ["Genesis 22:19"], places: ["JBC-CR-PLACE-BEERSHEBA-001"] },
    { domain: "기초 지리", period: "검증 시대 B", story: "검증 이야기 B", scene: "검증 장면 B", passage_refs: ["Genesis 21:31"], places: ["JBC-CR-PLACE-BEERSHEBA-001"] }
  ] } }], text: [], tables: [] };
  const n = normalize(p, overlay, { relPath: "fixture/nav.md" }).record, v = validate(n, p, { krv, expected_identity: "JBC-CR-PLACE-BEERSHEBA-001" });
  ok(Array.isArray(n.navigation) && n.navigation.length === 2 && n.navigation.every((x) => x.places[0] === n.stable_id), JSON.stringify(n.navigation));
  ok(v.ok, JSON.stringify(v.errors)); return ["paths=2", "stable_id reused="+n.stable_id];
});

t("P06", "relations are kept as written and never linked by name", () => { ok(rec.relations.every((r) => r.resolved === false && r.from_id === null), "resolved relation"); return ["unresolved endpoints=" + rec.relations.length]; });

t("P07", "Scripture Entity Index: only DIRECT_MENTION verses where the KRV text contains the name", () => {
  const ix = base.index, keys = Object.keys(ix.entries); ok(keys.join() === "gen-21:14,gen-21:31,gen-21:32,gen-21:33,gen-22:19,gen-26:23,gen-26:33,gen-28:10,gen-46:1,gen-46:5".split(",").filter((k) => keys.includes(k)).join() || keys.length === 10, keys.join());
  let bad = 0; for (const k of keys) { const [pid, v] = k.split(/[:]/), [b, c] = [pid.split("-")[0], +pid.split("-")[1]], text = krv.books.find((x) => x.id === b).chapters[c - 1][+v - 1]; for (const e of ix.entries[k]) for (const sp of e.spans) if (text.slice(sp[0], sp[1]) !== e.surface) bad++; }
  ok(bad === 0, "span mismatch"); ok(ix.stats.related_links_not_tagged.length === 2, "related links must not be tagged"); ok(!keys.some((k) => /^gen-20:/.test(k) || /^gen-26:(\d|1\d|2[0-2]):?$/.test(k) && +k.split(":")[1] <= 22), "related/contextual verse tagged"); ok(ix.meta.krv_modified === false, "krv flag"); return ["tagged verses=" + keys.length + " of " + ix.stats.verses_in_ranges + " in direct ranges", "untagged (no surface)=" + ix.stats.verses_without_surface.join(",")];
});

t("P08", "generated files on disk equal a fresh ingest of all records (deterministic, no hand edits)", () => {
  const tmpd = fs.mkdtempSync(path.join(os.tmpdir(), "jbc-det-")), r = ingest({ krv, dataDir: tmpd, outDir: tmpd, syncFile: path.join(tmpd, "sync.json"), writeArtifacts: false }); ok(r.wrote && r.records.every((x) => x.ok), "ingest");
  const a = [sha(dataFile), sha(idxFile)], b = [sha(path.join(tmpd, "projection.research.js")), sha(path.join(tmpd, "scripture.index.js"))]; ok(a.join() === b.join(), "not deterministic / hand edited"); return ["projection sha=" + a[0].slice(0, 12), "index sha=" + a[1].slice(0, 12)];
});

// ---- negatives (validator must fail closed) ----
const neg = (id, name, mutate, expectId) => t(id, "negative: " + name, () => {
  const parsed = base.parsed, r = clone(base.norm.record), p = clone(parsed); mutate(r, p); const v = validate(r, p, { krv });
  ok(!v.ok && v.errors.some((e) => e.startsWith(expectId)), "expected " + expectId + ", got " + JSON.stringify(v.errors)); return ["rejected with " + v.errors.filter((e) => e.startsWith(expectId))[0]];
});
neg("N01", "missing stable_id", (r) => { r.stable_id = ""; }, "V01");
neg("N02", "coordinate invented for the unlocated biblical place", (r) => { r.coordinates = { lat: 31.25, lon: 34.79 }; }, "V10");
neg("N03", "passage ref outside the KRV", (r) => { r.passage_links[0].v2 = 999; }, "V14");
neg("N04", "claim without an evidence locator", (r) => { r.claims[0].locator = ""; }, "V16");
neg("N05", "media without a license", (r) => { r.media[1].license = ""; }, "V20");
neg("N06", "VERIFY dropped while status says WITH_VERIFY", (r) => { r.verify = []; }, "V18");
neg("N07", "pipeline-created preview URL (no resolver basis for it)", (r) => { r.media[0].preview_url = "https://upload.wikimedia.org/x.jpg"; }, "V35");
neg("N08", "BAT01 identity reuse in the note", (r, p) => { Object.values(p.sections).flatMap((s) => s.yaml).map((b) => b.data).find((d) => d && d.Place).Place.identity_lineage.BAT01_PLACE_reuse = true; }, "V09");
neg("N09", "relation resolved by name", (r) => { r.relations[0].resolved = true; r.relations[0].from_id = "JBC-CR-PERSON-ABRAHAM-001"; }, "V23");
neg("N10", "candidate site equated with the biblical place", (r) => { r.candidates[0].equivalence_locked = true; }, "V12");
neg("N13", "candidate coordinate outside valid geographic range", (r) => { r.candidates[0].lat = 200; }, "V26");
neg("N14", "media without an explicit target_ref", (r) => { r.media[0].target_ref = null; }, "V27");
neg("N15", "media target_ref that resolves to no record id", (r) => { r.media[0].target_ref.ref = "JBC-CR-SITE-NOWHERE-001"; }, "V27");
neg("N16", "modern-city photo bound to the archaeological site", (r) => { r.media[2].target_ref.ref = "JBC-CR-SITE-TEL_BEER_SHEVA-001"; }, "V27");
neg("N17", "media bound to the biblical place itself", (r) => { r.media[0].target_ref.ref = r.stable_id; }, "V27");
neg("N18", "license that is not normalized (rights unvalidated)", (r) => { r.media[1].rights = { validated: false, status: "UNNORMALIZED", license_code: null, display_clearance: false }; }, "V28");
neg("N19", "CLEARED status without resolver clearance basis", (r) => { delete r.media[0].rights.clearance_basis; }, "V28");
neg("N20", "attribution missing the creator", (r) => { r.media[1].attribution = "Wikimedia Commons, CC BY-SA 3.0."; }, "V28");
neg("N21", "source_url on a foreign host", (r) => { r.media[0].source_url = "https://example.com/wiki/File:x.jpg"; r.media[0].source_url_verified = true; }, "V29");
neg("N22", "source_url page that does not match the media file", (r) => { r.media[0].source_url = "https://commons.wikimedia.org/wiki/File:Other.jpg"; r.media[0].source_url_verified = true; }, "V29");
neg("N23", "verified flag without a source URL", (r) => { r.media[0].source_url = null; r.media[0].source_url_verified = true; }, "V29");
neg("N24", "image payload field on a media asset", (r) => { r.media[0].image_url = "https://upload.wikimedia.org/x.jpg"; }, "V30");
neg("N25", "script in a media caption", (r) => { r.media[0].reader_caption = "<script>alert(1)</script>"; }, "V30");
neg("N26", "display mode outside the allowed attribution_only/image states", (r) => { r.media[0].display_mode = "manual"; }, "V30");
neg("N27", "two representative assets", (r) => { r.media[1].representative = true; }, "V31");
neg("N28", "stale per-media hash", (r) => { r.media[0].creator = "Someone Else"; r.media[0].attribution = "Someone Else, CC BY-SA 4.0."; }, "V32");
neg("N11", "registry effect not NONE", (r) => { r.authority.registry_effect = "MUTATED"; }, "V08");
neg("N41", "structured rights license differs from the media license", (r) => { r.media[0].declared_rights.license = "CC BY 4.0"; }, "V28");

const negG = (id, name, mutate, expectId) => t(id, "negative: " + name, () => {
  const r = clone(gresBase.norm.record), p = clone(gresBase.parsed); mutate(r, p); const v = validate(r, p, { krv }); ok(!v.ok && v.errors.some((e) => e.startsWith(expectId)), "expected " + expectId + ", got " + JSON.stringify(v.errors)); return ["rejected with " + v.errors.filter((e) => e.startsWith(expectId))[0].slice(0, 120)];
});
const gresBase = run({ source: GERAR, krv, overlay: path.join(ROOT, "data", "projection.overlay.gerar.json"), syncFile: path.join(os.tmpdir(), "jbc-none-sync.json"), approval: { value: "CAPTAIN_APPROVED", source: "t" }, expected: "JBC-CR-PLACE-GERAR-001" });
negG("N29", "preview URL on a foreign host", (r) => { r.media[0].preview_url = "https://evil.example/a.jpg"; }, "V35");
negG("N30", "preview URL without a resolution", (r) => { delete r.media[0].resolution; }, "V35");
negG("N31", "preview URL that differs from the resolved thumbnail", (r) => { r.media[0].preview_url = r.media[0].preview_url.replace("960px", "1280px"); }, "V35");
negG("N32", "preview present although the API license did not match", (r) => { r.media[0].resolution.license_match = false; }, "V35");
negG("N33", "preview present although the API creator did not match", (r) => { r.media[0].resolution.creator_match = false; }, "V35");
negG("N34", "preview present although the API source page did not match", (r) => { r.media[0].resolution.source_page_match = false; }, "V35");
negG("N35", "preview of an svg / non-raster mime type", (r) => { r.media[0].resolution.mime = "image/svg+xml"; }, "V35");
negG("N36", "preview present although the API lists restrictions", (r) => { r.media[0].resolution.restrictions = "trademarked"; }, "V35");
negG("N37", "preview present but rights not CLEARED", (r) => { r.media[0].rights.status = "REUSE_NO_ATTRIBUTION_REQUIRED"; r.media[0].rights.display_clearance = false; }, "V35");
negG("N38", "CLEARED whose declared rights status is not a clearable one", (r) => { r.media[0].rights.clearance_basis.declared_rights_status = "reusable with attribution"; }, "V28");
negG("N39", "eligible resolution but no preview applied", (r) => { r.media[0].preview_url = null; r.media[0].display_mode = "attribution_only"; r.media[0].rights.status = "REUSE_NO_ATTRIBUTION_REQUIRED"; r.media[0].rights.display_clearance = false; delete r.media[0].rights.clearance_basis; }, "V35");
negG("N40", "preview URL over plain http", (r) => { r.media[0].preview_url = r.media[0].preview_url.replace("https://", "http://"); r.media[0].resolution.thumb_url = r.media[0].preview_url; }, "V35");

negG("N42", "spatial read model missing", (r) => { delete r.spatial; }, "V36");
negG("N43", "a primary marker without a verified coordinate", (r) => { r.spatial.primary.marker = { render: true, reason: "forced" }; }, "V36");
negG("N44", "a candidate marker the marker rule does not allow (unrecognized status)", (r) => { r.spatial.sites[0].marker = { render: true, style: "site", reason: "forced" }; }, "V36");
negG("N45", "an invented region boundary", (r) => { r.spatial.region.boundary = { type: "Polygon" }; }, "V36");
negG("N46", "an invented route geometry", (r) => { r.spatial.routes[0].geometry = [[31, 34], [31.2, 34.8]]; }, "V36");
negG("N47", "certainty dimensions merged / altered", (r) => { r.spatial.certainty.coordinate = r.spatial.certainty.identity; }, "V36");
negG("N48", "VERIFY/HOLD dropped from the spatial model", (r) => { r.spatial.verify_hold.verify = []; }, "V36");
negG("N49", "a candidate coordinate changed after normalization", (r) => { r.spatial.sites[0].lat = 31.5; }, "V36");
negG("N50", "a region given a point", (r) => { r.spatial.region.lat = 31.2; r.spatial.region.lon = 34.8; }, "V36");

t("N12", "fail-closed on the real ingest path: a broken note never replaces the last known good projection", () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "jbc-pl-")), mir = path.join(dir, "mirror"), dd = path.join(dir, "data"); fs.mkdirSync(path.join(mir, "브엘세바"), { recursive: true }); fs.mkdirSync(path.join(mir, "그랄"), { recursive: true }); fs.mkdirSync(dd);
  fs.writeFileSync(path.join(mir, "브엘세바", path.basename(SOURCE)), srcText.replace("stable_id: JBC-CR-PLACE-BEERSHEBA-001", "stable_id: WRONG")); fs.copyFileSync(GERAR, path.join(mir, "그랄", path.basename(GERAR)));
  fs.copyFileSync(dataFile, path.join(dd, "projection.research.js")); fs.copyFileSync(idxFile, path.join(dd, "scripture.index.js"));
  const vm0 = require("vm"), beforeBox = { window: {} }; vm0.runInNewContext(fs.readFileSync(path.join(dd, "projection.research.js"), "utf8"), beforeBox); const beforeRec = clone(beforeBox.window.BVC_PROJECTION.places["JBC-CR-PLACE-BEERSHEBA-001"]);
  const before = [sha(dataFile), sha(idxFile)], r = ingest({ krv, vault: false, mirrorRoot: mir, dataDir: dd, outDir: dir, syncFile: path.join(dir, "sync.json"), writeArtifacts: false });
  const bs = r.records.find((x) => /BEERSHEBA/.test(x.document_id)), gr = r.records.find((x) => /GERAR/.test(x.document_id)); ok(bs && !bs.ok && bs.preserved_last_known_good && gr && gr.ok, "beersheba rejected + preserved, gerar still projected: " + JSON.stringify(r.records.map((x) => [x.document_id, x.ok])));
  const now = require("vm"); const box = { window: {} }; now.runInNewContext(fs.readFileSync(path.join(dd, "projection.research.js"), "utf8"), box); const kept = box.window.BVC_PROJECTION.places["JBC-CR-PLACE-BEERSHEBA-001"]; ok(JSON.stringify(kept) === JSON.stringify(beforeRec), "last known good Beersheba entry must be kept unchanged");
  ok([sha(dataFile), sha(idxFile)].join() === before.join(), "the real data files were modified"); return ["errors=" + bs.errors.join(" | ").slice(0, 200), "preserved=" + r.preserved_last_known_good];
});

t("O01", "Obsidian syntax: YAML frontmatter, [[wikilink|alias]] and ![[embed]] are handled without changing the note", () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "jbc-ob-")), f = path.join(dir, "n.md"); fs.writeFileSync(f, "---\ntitle: Test\ntags: [a]\nlist:\n  - x\n---\n# H\nSee [[Some Note|alias]] and [[Plain]] ![[img.png]] end.\n\n```yaml\nk: v\nn:\n  - 1\n  - two\n```\n");
  const p = parseNote(f); ok(p.frontmatter && p.frontmatter.title === "Test" && p.frontmatter.list[0] === "x", "frontmatter"); const h = p.sections["H"]; ok(h.text[0] === "See alias and Plain end.", "wikilinks: " + h.text[0]); ok(h.yaml[0].data.k === "v" && h.yaml[0].data.n[1] === "two", "yaml block"); ok(sha(f) === p.source.sha256, "hash"); return ["frontmatter+wikilinks+yaml ok"];
});

// ---- media-specific tests ----
const all0 = ingest({ dryRun: true, krv, syncFile: path.join(os.tmpdir(), "jbc-none-sync.json") }), BS0 = all0.projection.places["JBC-CR-PLACE-BEERSHEBA-001"];
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "jbc-media-")), withOverlay = (f) => { const o = clone(overlay); f(o); const file = path.join(tmp, "overlay-" + Math.random().toString(36).slice(2) + ".json"); fs.writeFileSync(file, JSON.stringify(o)); return file; };
const baseSync = path.join(tmp, "base-sync.json"); fs.writeFileSync(baseSync, JSON.stringify({ records: { [rec.stable_id]: Object.fromEntries(rec.media.map((a) => [a.id, a.content_hash])) } }));
t("M01", "expected result: discovered 3, bound 3, structured rights cleared, resolver previews enabled, payloads / invented URLs / unsafe / source mutations 0", () => { const r = run({ dryRun: true, krv, syncFile: baseSync }).mediaReport; const exp = { discovered: 3, bound: 3, rights_validated: 3, attribution_only: 0, preview_urls: 3, images_enabled: 3, resolved: 3, quarantined: 0, image_payloads: 0, invented_urls: 0, invented_preview_urls: 0, unsafe_payloads: 0, source_mutations: 0 }; ok(Object.keys(exp).every((k) => r[k] === exp[k]), JSON.stringify(r)); return [JSON.stringify(exp)]; });
t("M02", "bindings are explicit: each asset carries a target_ref (overlay_explicit) that resolves to a record id; none inferred", () => { const ids = new Set([rec.stable_id].concat(rec.candidates.map((c) => c.id))); ok(rec.media.every((a) => a.target_ref && ids.has(a.target_ref.ref) && a.target_ref.binding === "overlay_explicit"), "binding"); ok(rec.media.map((a) => a.target_ref.ref).join() === "JBC-CR-SITE-TEL_BEER_SHEVA-001,JBC-CR-SITE-TEL_BEER_SHEVA-001,JBC-CR-PLACE-BEERSHEBA_MODERN-001", "targets"); return rec.media.map((a) => a.id + " -> " + a.target_ref.ref); });
t("M03", "rights normalized per exact declared license and cleared only through the resolver", () => { const c = rec.media.map((a) => a.rights.license_code + "/sa=" + a.rights.share_alike); ok(c.join() === "CC-BY-SA-4.0/sa=true,CC-BY-SA-3.0/sa=true,CC-BY-4.0/sa=false", c.join()); ok(rec.media.every((a) => a.declared_rights.status === "CLEARED" && a.declared_rights.license === a.license && a.rights.validated && a.rights.attribution_required && a.rights.display_clearance === true && a.rights.status === "CLEARED" && a.rights.clearance_basis.resolver === "wikimedia_commons_api"), "clearance"); return c; });
t("M04", "Beersheba source pages are explicit (overlay, taken from the Commons API answer), validator-verified, never built from file names", () => {
  const ov = JSON.parse(fs.readFileSync(OVERLAY, "utf8")); ok(rec.media.every((a) => a.source_url === ov.media_bindings[a.id].source_url && a.source_url_verified === true), "urls = overlay, verified"); ok(/Commons API/.test(ov._source_url_provenance), "provenance recorded");
  for (const a of rec.media) { const c = JSON.parse(fs.readFileSync(resolver.cacheFile(resolver.CACHE_DIR, a.file), "utf8")), d = c.response.query.pages[0].imageinfo[0].descriptionurl; ok(d === a.source_url, "overlay URL equals the API's own page URL: " + a.id); }
  ok(rec.media.every((a) => a.preview_url && a.resolution && a.resolution.thumb_url === a.preview_url), "preview must be resolver-derived after structured clearance"); return rec.media.map((a) => a.id + " verified");
});
t("M05", "an author flag is never authority (no URL → not verified even if flagged); a mismatching URL is rejected and only that asset is quarantined", () => {
  const f = withOverlay((o) => { delete o.media_bindings["JBC-MEDIA-BS-002"].source_url; o.media_bindings["JBC-MEDIA-BS-002"].source_url_verified = "true"; });
  const r = run({ krv, overlay: f, syncFile: baseSync }), m = r.norm.record.media; ok(r.validation.ok && r.quarantined.length === 0, JSON.stringify(r.quarantined)); ok(m[0].source_url_verified === true && m[1].source_url === null && m[1].source_url_verified === false, "generated verification / ignored author flag"); ok(r.mediaReport.invented_urls === 0, "counted as invented");
  const bad = withOverlay((o) => { o.media_bindings["JBC-MEDIA-BS-001"].source_url = "https://commons.wikimedia.org/wiki/File:Other.jpg"; }), rb = run({ krv, overlay: bad, syncFile: baseSync }); ok(rb.validation.ok && rb.quarantined.length === 1 && /V29/.test(rb.quarantined[0].errors[0]), "mismatching URL must be quarantined: " + JSON.stringify(rb.quarantined)); return [m[0].source_url, "mismatch → " + rb.quarantined[0].errors[0].slice(0, 80)];
});
t("M06", "representative resolution: exactly one (BS-001); the modern-city photo and the altar photo are never representative", () => { ok(rec.representative_media_id === "JBC-MEDIA-BS-001" && rec.media.filter((a) => a.representative).map((a) => a.id).join() === "JBC-MEDIA-BS-001", "rep"); return ["representative=" + rec.representative_media_id]; });
t("M07", "failure isolation: one asset with a bad binding is quarantined; siblings and the record still pass", () => { const f = withOverlay((o) => { o.media_bindings["JBC-MEDIA-BS-002"].target_ref = "JBC-CR-SITE-NOWHERE-001"; }); const r = run({ dryRun: true, krv, overlay: f, syncFile: baseSync }); ok(r.validation.ok, "record should stay valid"); ok(r.quarantined.length === 1 && r.quarantined[0].id === "JBC-MEDIA-BS-002", JSON.stringify(r.quarantined)); ok(r.norm.record.media.map((a) => a.id).join() === "JBC-MEDIA-BS-001,JBC-MEDIA-BS-003" && r.sync.removed.join() === "JBC-MEDIA-BS-002" && r.sync.quarantined.join() === "JBC-MEDIA-BS-002", "siblings/sync"); return [r.quarantined[0].errors.join(" | ")]; });
t("M08", "incremental sync: unchanged means all unchanged; changing one asset's metadata changes only that asset's hash", () => { const same = run({ dryRun: true, krv, syncFile: baseSync }).sync; ok(same.unchanged.length === 3 && !same.added.length && !same.changed.length && !same.removed.length, JSON.stringify(same)); const f = withOverlay((o) => { o.media_captions["JBC-MEDIA-BS-003"] += " (수정)"; }); const ch = run({ dryRun: true, krv, overlay: f, syncFile: baseSync }).sync; ok(ch.changed.join() === "JBC-MEDIA-BS-003" && ch.unchanged.length === 2, JSON.stringify(ch)); const empty = run({ dryRun: true, krv, syncFile: path.join(tmp, "none.json") }).sync; ok(empty.added.length === 3, "first run adds all"); return ["unchanged=3", "changed=" + ch.changed, "first run added=3"]; });
t("M09", "sources are never mutated by a run, and dry runs write no manifest", () => { const h = sha(SOURCE), o = sha(OVERLAY), sf = path.join(tmp, "dry-sync.json"); ingest({ dryRun: true, krv, syncFile: sf }); ok(sha(SOURCE) === h && sha(OVERLAY) === o, "source/overlay changed"); ok(!fs.existsSync(sf), "dry run wrote a manifest"); return ["source sha unchanged " + h.slice(0, 12)]; });
t("M10", "the projection carries no image bytes; Beersheba previews are resolver-derived after structured rights clearance", () => {
  const txt = fs.readFileSync(dataFile, "utf8"); ok(!/data:image|base64|<img|<script/i.test(txt), "payload in projection"); ok(BS0.media.every((a) => a.preview_url && a.display_mode === "image" && a.declared_rights.status === "CLEARED"), "Beersheba media");
  const prevs = Object.values(all0.projection.places).flatMap((r) => r.media).filter((a) => a.preview_url); ok(prevs.every((a) => a.resolution && a.resolution.thumb_url === a.preview_url), "preview not from resolver"); return ["previews=" + prevs.length + " (all resolver-derived)"]; });

// ---- multi-record ingest tests (Beersheba + Gerar through the one pipeline) ----
const cfg = loadConfig(), all = ingest({ dryRun: true, krv, syncFile: path.join(tmp, "all-sync.json") }), G = all.projection.places["JBC-CR-PLACE-GERAR-001"], BS = all.projection.places["JBC-CR-PLACE-BEERSHEBA-001"];
const gres = all.results.find((r) => r.doc && r.doc.stable_id === "JBC-CR-PLACE-GERAR-001"), gsrc = fs.readFileSync(GERAR, "utf8");
const tmpMirror = (edit) => { const d = fs.mkdtempSync(path.join(os.tmpdir(), "jbc-mir-")); fs.mkdirSync(path.join(d, "브엘세바"), { recursive: true }); fs.mkdirSync(path.join(d, "그랄"), { recursive: true }); fs.copyFileSync(SOURCE, path.join(d, "브엘세바", path.basename(SOURCE))); fs.writeFileSync(path.join(d, "그랄", path.basename(GERAR)), edit ? edit(gsrc) : gsrc); return d; };
const gerarOnly = (edit, opts2) => { const d = tmpMirror(edit); return ingest(Object.assign({ dryRun: true, krv, vault: false, mirrorRoot: d, syncFile: path.join(tmp, "g-sync.json") }, opts2 || {})).results.find((r) => r.doc && /GERAR/.test(r.doc.document_id)); };
t("I01", "discovery: research documents are found under 02_연구물; the approved Full Place Profile may be DETAIL_ONLY while core projection records continue through the shared pipeline", () => {
  const d = discover(cfg, { krv }); ok(d.found.map((f) => f.vrel).join() === "02_연구물/브엘세바/JBC_BEERSHEBA_CONNECTED_WORBS_20260930_01.md,02_연구물/브엘세바/JBC_BEERSHEBA_FULL_CANONICAL_PLACE_PROFILE_WORBS_20261004_01.md,02_연구물/그랄/JBC_GERAR_CONNECTED_WORBS_20260930_01.md,02_연구물/그랄/JBC_GERAR_FULL_CANONICAL_PLACE_PROFILE_WORBS_20261005_01.md", d.found.map((f) => f.vrel).join());
  ok(d.skipped.some((x) => /JBC_BEERSHEBA_CONNECTED_WORBS_20260930_01 1\.md/.test(x.path) && /header id does not equal/.test(x.reason)), "duplicate must be skipped by identity/file-name mismatch: " + JSON.stringify(d.skipped));
  const v = fs.mkdtempSync(path.join(os.tmpdir(), "jbc-vault-")), w = (rel, txt) => { const f = path.join(v, rel); fs.mkdirSync(path.dirname(f), { recursive: true }); fs.writeFileSync(f, txt); }; fs.mkdirSync(path.join(v, "02_연구물", "브엘세바"), { recursive: true }); fs.mkdirSync(path.join(v, "02_연구물", "아말렉"), { recursive: true });   // every configured include folder must exist (Amalek is now configured)
  w("02_연구물/그랄/" + path.basename(GERAR), gsrc); w("02_연구물/그랄/99_운영문서/copy.md", gsrc); w("99_운영문서/" + path.basename(GERAR), gsrc); w("01_소스들/" + path.basename(GERAR), gsrc); w("03_산출물/" + path.basename(GERAR), gsrc); w("02_연구물/다른곳/" + path.basename(SOURCE), srcText);
  const dv = discover(cfg, { vault: v }); ok(dv.found.map((f) => f.vrel).join() === "02_연구물/다른곳/" + path.basename(SOURCE) + ",02_연구물/그랄/" + path.basename(GERAR), "vault: auto-discovery under the 02_연구물 root (any sub-folder), nothing outside it: " + dv.found.map((f) => f.vrel).join()); ok(dv.excluded.join() === "02_연구물/그랄/99_운영문서/copy.md", "nested excluded folder skipped: " + dv.excluded.join()); ok(dv.scanned.some((s) => s.resolved_from === "vault"), "vault used when present");
  ok(cfg.records["JBC_BEERSHEBA_FULL_CANONICAL_PLACE_PROFILE_WORBS_20261004_01"].projection_mode === "DETAIL_ONLY" && cfg.records["JBC_GERAR_FULL_CANONICAL_PLACE_PROFILE_WORBS_20261005_01"].projection_mode === "DETAIL_ONLY", "Full Place Profiles must be explicitly routed to the common detail projection stage");
  return ["found=4 including two DETAIL_ONLY Full Place Profiles", "skipped gate doc", "vault excluded=" + dv.excluded.join()];
});
t("I02", "both records go through the same pipeline: identity preserved, 35/35 checks each, one combined projection", () => {
  ok(all.records.length === 2 && all.records.every((r) => r.ok && r.checks === 35), JSON.stringify(all.records.map((r) => [r.document_id, r.ok, r.checks]))); ok(Object.keys(all.projection.places).join() === "JBC-CR-PLACE-BEERSHEBA-001,JBC-CR-PLACE-GERAR-001", "places"); ok(BS.legacy_key === "beersheba" && G.legacy_key === "gerar", "legacy keys");
  ok(all.projection.meta.records.length === 2 && all.projection.meta.generated_by === "tools/pipeline/run.js v0.2", "one generator"); ok(G.stable_id === cfg.records["JBC_GERAR_CONNECTED_WORBS_20260930_01"].expected_identity, "identity as configured");
  const files = fs.readdirSync(__dirname).filter((f) => /\.js$/.test(f)); ok(!files.some((f) => /gerar|beersheba/i.test(f)), "no record-specific pipeline files: " + files.join()); return ["places=2", "pipeline files=" + files.join(", ")];
});
t("I03", "Beersheba result is unchanged by the multi-record ingest (record and Scripture index equal the pre-ingest baseline; additive keys only)", () => {
  const baseRec = JSON.parse(fs.readFileSync(path.join(__dirname, "baseline", "beersheba.record.pre-ingest.json"), "utf8")), c = clone(BS); delete c.hero_subject; delete c.activation; delete c.reader.published;  /* consumer visibility metadata is an additive overlay-controlled key */ delete c.connected; delete c.spatial; ["research_status","identity_binding_status","relation_binding_status","media_binding_status","geometry_status","projection_status"].forEach((k) => delete c[k]); const stripM = (r0) => { delete r0.source_refs[0].path; delete r0.source_refs[0].sha256; r0.media.forEach((a) => { ["source_url", "source_url_verified", "resolution", "content_hash", "preview_url", "display_mode", "rights", "declared_rights", "rights_note", "attribution_derived", "attribution_composed"].forEach((k) => delete a[k]); }); return r0; }; ok(JSON.stringify(stripM(baseRec)) === JSON.stringify(stripM(c)), "record differs from baseline outside canonical provenance and approved media metadata/rights fields");
  const baseIdx = JSON.parse(fs.readFileSync(path.join(__dirname, "baseline", "beersheba.index.pre-ingest.json"), "utf8")), got = {}; for (const k of Object.keys(all.index.entries)) { const e = all.index.entries[k].filter((x) => x.stable_id === "JBC-CR-PLACE-BEERSHEBA-001"); if (e.length) got[k] = e; } ok(JSON.stringify(got) === JSON.stringify(baseIdx), "Beersheba index entries differ"); return ["additive keys: hero_subject, connected, reader.published, activation"];
});
t("I04", "approval: the note says PENDING_CAPTAIN_REVIEW; without the configured CAPTAIN_APPROVED override the record is rejected; with it the override and the note's own value are both recorded", () => {
  const noOv = run({ source: GERAR, krv, overlay: path.join(ROOT, cfg.records["JBC_GERAR_CONNECTED_WORBS_20260930_01"].overlay), syncFile: path.join(tmp, "x.json"), expected: "JBC-CR-PLACE-GERAR-001" }); ok(!noOv.validation.ok && noOv.validation.errors.some((e) => e.startsWith("V33")), "must be rejected without approval: " + noOv.validation.errors);
  ok(G.authority.approval === "CAPTAIN_APPROVED" && G.authority.note_approval_status === "PENDING_CAPTAIN_REVIEW" && /control instruction/.test(G.authority.approval_source), "override recorded with the note's own status"); ok(G.authority.registry_effect === "NONE" && G.authority.BAT01_crosswalk === "NOT_PERFORMED", "registry untouched"); return ["approval=" + G.authority.approval, "note=" + G.authority.note_approval_status];
});
t("I05", "identity: a wrong expected identity is rejected, and same-name places are never merged (Beersheba/Gerar stay separate ids; relations to other names stay unresolved)", () => {
  const r = run({ source: GERAR, krv, overlay: path.join(ROOT, cfg.records["JBC_GERAR_CONNECTED_WORBS_20260930_01"].overlay), syncFile: path.join(tmp, "x.json"), approval: { value: "CAPTAIN_APPROVED", source: "t" }, expected: "JBC-CR-PLACE-BEERSHEBA-001" }); ok(!r.validation.ok && r.validation.errors.some((e) => e.startsWith("V34")), "identity mismatch must fail");
  ok(G.relations.length === 15, "relation rows kept as written"); const bound = G.relations.filter((x) => x.resolved); ok(bound.length === 1 && bound[0].to === "Beersheba" && bound[0].to_id === "JBC-CR-PLACE-BEERSHEBA-001" && bound[0].binding.rule === "record_declared_identity", "only the Beersheba row binds, and only through the identity the Gerar note itself declares (known_parent_asset_identity), never by name"); ok(G.relations.filter((x) => !x.resolved).every((x) => x.from_id === null) && G.relations.filter((x) => x.to_id && !x.resolved).every((x) => x.to === "Gerar" || x.to === "Biblical Gerar"), "every other row stays unresolved (self-references keep their own id only)"); ok(G.connected.places.find((p) => p.name === "Beersheba").known_parent_asset_identity === "JBC-CR-PLACE-BEERSHEBA-001", "parent identity carried exactly as written"); return ["V34 rejects", "relations bound=1 (declared identity), unresolved=14"];
});
t("I06", "geography (Gerar): no primary coordinate, candidate coordinates only as supplied, status preserved (none invented), competing views kept, nothing eligible for an exact pin", () => {
  ok(G.coordinates === null && G.coordinate_status === "NOT_ASSIGNED" && G.location.reader_status === "DISPUTED", "primary"); ok(G.candidates.length === 4 && G.candidates.every((c) => c.id === null && c.status === null && c.equivalence_locked === false), "candidates keep no invented id/status and stay non-equivalent");
  const c = G.candidates; ok(c[0].lat === 31.3821 && c[0].lon === 34.6065 && c[1].lat === 31.38724 && c[2].lon === 34.6816 && c[3].lat === null && c[3].lon === null, "coordinates exactly as written; Tell el-Far'a South has none"); ok(c.map((x) => x.candidate_role).join() === "LEADING_LOCATION_HYPOTHESIS,HISTORICAL_AND_REVIVED_COMPETING_IDENTIFICATION,OLDER_COMPETING_IDENTIFICATION,SCHOLARLY_PROPOSAL", "roles preserved");
  ok(G.competing_views.length === 4 && G.verify.length === 6 && G.hold.length === 6 && G.hold.every((h) => typeof h === "string"), "competing views / VERIFY / HOLD preserved"); return ["candidates=4 (3 with coordinates)", "verify=6 hold=6"];
});
t("I07", "scripture (Gerar): only literal 그랄 in DIRECT_MENTION verses; related / contextual / variant passages create no tags", () => {
  const keys = Object.keys(all.index.entries).filter((k) => all.index.entries[k].some((e) => e.stable_id === G.stable_id)); ok(keys.join() === "gen-10:19,gen-20:1,gen-20:2,gen-26:1,gen-26:6,gen-26:17,gen-26:20,gen-26:26,2ch-14:13,2ch-14:14", keys.join());
  for (const k of keys) { const [pid, v] = k.split(":"), b = pid.split("-"), text = krv.books.find((x) => x.id === b[0]).chapters[+b[1] - 1][+v - 1]; for (const e of all.index.entries[k].filter((x) => x.stable_id === G.stable_id)) { ok(e.surface === "그랄" && e.spans.length > 0 && e.spans.every((sp) => text.slice(sp[0], sp[1]) === "그랄"), "literal span " + k); } }
  ok(!keys.some((k) => /^gen-(20:([3-9]|1\d)|21|26:(2[1-5]|2[7-9]|3\d))$/.test(k)), "a related/contextual verse was tagged"); ok(G.passage_links.filter((l) => l.group === "related").length === 3 && gres.norm.skipped.some((s) => /TEXTUAL_VARIANT/.test(s)) && gres.norm.skipped.some((s) => /CONTEXTUAL/.test(s)), "related kept as links only; variants/contextual skipped"); return ["tagged verses=" + keys.length];
});
t("I08", "navigation: neither note carries navigation metadata → null with a warning, nothing invented (no period / story / scene)", () => { ok(G.navigation === null && BS.navigation === null, "navigation must be null"); ok(gres.norm.warnings.some((w) => /navigation metadata/.test(w)) && gres.validation.warnings.some((w) => /V25/.test(w)), "warned"); ok(!G.connected.events.some((e) => e.period || e.story), "no period/story on events"); return [gres.norm.warnings.join(" | ")]; });
t("I09", "media (Gerar): 2 assets bound explicitly, rights normalized, source page verified by the validator, preview derived only from the cached Commons API answer, images enabled for the gate, one representative", () => {
  const r = gres.mediaReport; ok(r.discovered === 2 && r.bound === 2 && r.rights_validated === 2 && r.image_payloads === 0 && r.invented_urls === 0 && r.invented_preview_urls === 0 && r.unsafe_payloads === 0 && r.source_mutations === 0 && r.quarantined === 0 && r.preview_urls === 2 && r.images_enabled === 2 && r.resolved === 2, JSON.stringify(r));
  const m = G.media; ok(m.every((a) => a.source_url_verified === true && gsrc.indexOf(a.source_url) >= 0 && a.rights.license_code === "CC0-1.0" && a.rights.status === "CLEARED" && a.rights.clearance_basis.resolver === "wikimedia_commons_api" && a.target_ref.ref === G.stable_id && a.display_mode === "image" && a.resolution.verified === true), "media contract");
  ok(G.representative_media_id === "JBC-MEDIA-GR-001" && m[1].representative === false, "representative"); ok(m[0].reader_caption.indexOf("확정되지 않았다") > 0 && m[1].reader_caption === null, "candidate-only caption from the note, none invented"); return ["representative=" + G.representative_media_id, "images enabled: " + m.length];
});
t("I10", "media safety (Gerar): a source page that does not match the file is quarantined, siblings and the record survive; a picture bound to the biblical place without a candidate-only declaration is rejected", () => {
  const bad = gerarOnly((t0) => t0.replace("https://commons.wikimedia.org/wiki/File:תל_הרור1.jpg", "https://commons.wikimedia.org/wiki/File:Other.jpg")); ok(bad.validation.ok && bad.quarantined.length === 1 && bad.quarantined[0].id === "JBC-MEDIA-GR-001" && bad.norm.record.media.length === 1 && bad.norm.record.representative_media_id === null, "isolation: " + JSON.stringify(bad.quarantined));
  const noDecl = gerarOnly((t0) => t0.replace(/biblical_Gerar: MEDIUM_CANDIDATE_ONLY/g, "biblical_Gerar: MEDIUM")); ok(noDecl.validation.ok && noDecl.quarantined.length === 2, "undeclared depiction must be quarantined: " + noDecl.quarantined.length); return ["mismatch → quarantined GR-001", "undeclared → 2 quarantined"];
});
t("I11", "missing data degrades cleanly: a Gerar copy without media, map_ready, PassageLink and quick_facts still validates or fails closed without inventing values", () => {
  const noMedia = gerarOnly((t0) => t0.replace(/MediaAsset:/g, "MediaAssetX:")); ok(noMedia.validation.ok && noMedia.norm.record.media.length === 0 && noMedia.norm.record.representative_media_id === null, "no media → none invented");
  const noMap = gerarOnly((t0) => t0.replace("map_ready:", "map_ready_x:")); ok(noMap.validation.ok && noMap.norm.record.candidates.length === 0 && noMap.norm.record.coordinates === null, "no map block → no candidates, no coordinates");
  const noLinks = gerarOnly((t0) => t0.replace("PassageLink:", "PassageLinkX:")); ok(!noLinks.validation.ok && noLinks.validation.errors.some((e) => /V14|V15/.test(e)), "no passage links → fail closed (direct link required)"); const noQf = gerarOnly((t0) => t0.replace("## quick_facts", "## quick_facts_x")); ok(noQf.validation.ok && noQf.norm.record.reader.quick_facts.length === 0, "no quick facts → empty, not invented"); return ["media/map/quick_facts absent → clean", "links absent → fail closed"];
});
t("I12", "safety: source notes, overlay files and KRV are byte-identical before and after an ingest; last known good is kept when a record breaks", () => {
  const files = [SOURCE, GERAR, path.join(ROOT, "data", "krv.js"), OVERLAY], before = files.map(sha); ingest({ dryRun: true, krv, syncFile: path.join(tmp, "s2.json") }); ok(files.map(sha).join() === before.join(), "a source/overlay/krv file changed");
  ok(all.index.meta.records.length === 5 && all.index.meta.records.filter((r) => /AMALEK/.test(r.record)).length === 1 && all.index.meta.records.filter((r) => /ACHAIA/.test(r.record)).length === 1 && all.index.meta.records.filter((r) => /ISAAC_PERSON_PROFILE/.test(r.record)).length === 1 && all.index.meta.krv_modified === false, "index meta (2 Place + 2 Region + 1 approved Person record)"); const g2 = gerarOnly((t0) => t0.replace("stable_id: JBC-CR-PLACE-GERAR-001", "stable_id: JBC-CR-PLACE-WRONG-001")); ok(!g2.validation.ok, "identity break must fail"); return ["hashes unchanged (" + files.length + " files)"];
});

t("I13", "every string in the Gerar record is traceable to the note, the Gerar overlay, the ingest config, or a declared derivation", () => {
  const ovG = JSON.parse(fs.readFileSync(path.join(ROOT, "data", "projection.overlay.gerar.json"), "utf8")), ovS = new Set(); (function w(o) { if (typeof o === "string") ovS.add(o); else if (o && typeof o === "object") Object.values(o).forEach(w); })(ovG);
  const flat = gsrc.replace(/\s+/g, " "), flatPlain = flat.replace(/`/g, "").replace(/\*\*/g, ""), exempt = /^(spatial\..+|authority\.(approval|approval_source)|source_refs\.0\.(path|sha256)|source_locator|VERIFY_HOLD\.reason|passage_links\.\d+\.(group|book)|media\.\d+\.(role|display_mode|content_hash|preview_url|attribution_derived|resolution\.\w+|rights\.(status|license_code|clearance_basis\.resolver)|target_ref\.binding)|connected\.people\.\d+\.(merge_with_other|binding\.(state|reason|source_locator))|connected\.events\.\d+\.binding\.(state|rule|reason|source_locator|target_id)|(research_status|identity_binding_status|relation_binding_status|media_binding_status|geometry_status|projection_status)|(relations|connected\.places)\.\d+\.binding\.(state|rule|reason|source_locator|target_id|candidates\.\d+|preserved_last_known_good)|competing_views\.\d+)$/, miss = [];
  (function w(o, p) { if (typeof o === "string") { if (!ovS.has(o) && !exempt.test(p) && flat.indexOf(o.replace(/\s+/g, " ")) < 0 && flatPlain.indexOf(o.replace(/\s+/g, " ")) < 0) miss.push(p + " = " + o.slice(0, 60)); } else if (Array.isArray(o)) o.forEach((v, i) => w(v, p ? p + "." + i : String(i))); else if (o && typeof o === "object") Object.keys(o).forEach((k) => w(o[k], p ? p + "." + k : k)); })(G, "");
  ok(!miss.length, "untraceable: " + JSON.stringify(miss)); ok(G.competing_views.every((v) => flatPlain.indexOf(v.split(" — ").slice(1).join(" — ").replace(/\s+/g, " ")) >= 0), "competing views are the note's own paragraphs"); return ["untraceable=0"];
});

// ---- Wikimedia resolver tests (injected API answers; no network) ----
const realCache = JSON.parse(fs.readFileSync(resolver.cacheFile(resolver.CACHE_DIR, rec0File()), "utf8")), realResp = realCache.response;
function rec0File() { return "File:תל הרור1.jpg"; }
const resp = (edit) => { const r = clone(realResp); edit(r); return r; }, pg = (r) => r.query.pages[0], ii = (r) => pg(r).imageinfo[0];
const cacheWith = (edit1, edit2) => { const d = fs.mkdtempSync(path.join(os.tmpdir(), "jbc-rc-")); [["File:תל הרור1.jpg", edit1], ["File:תל הרור נוף.jpg", edit2]].forEach(([title, ed]) => { if (!ed) return; const base = JSON.parse(fs.readFileSync(resolver.cacheFile(resolver.CACHE_DIR, title), "utf8")); const r = clone(base.response); ed(r); fs.writeFileSync(resolver.cacheFile(d, title), JSON.stringify({ title, request_url: "t", retrieved_at: "2026-01-01T00:00:00.000Z", response: r })); }); return d; };
const gRun = (cacheDir, o) => run(Object.assign({ source: GERAR, krv, overlay: path.join(ROOT, "data", "projection.overlay.gerar.json"), syncFile: path.join(tmp, "r-sync.json"), approval: { value: "CAPTAIN_APPROVED", source: "t" }, expected: "JBC-CR-PLACE-GERAR-001", cacheDir }, o || {}));
const noEd = (r) => {};
const held = (id, name, edit, why) => t(id, name, () => { const r = gRun(cacheWith(edit, noEd)), a = r.norm.record.media[0]; ok(r.validation.ok, "record must stay valid: " + JSON.stringify(r.validation.errors)); ok(a.preview_url === null && a.display_mode === "attribution_only" && a.rights.status !== "CLEARED" && a.rights.display_clearance === false && a.resolution.verified === false, "must stay attribution-only: " + JSON.stringify(a.resolution)); ok(why.test(a.resolution.reasons.join(" | ")), "reason: " + a.resolution.reasons.join(" | ")); ok(r.norm.record.media[1].preview_url !== null, "sibling resolved independently"); return [a.resolution.reasons[0].slice(0, 140)]; });
t("R01", "a verified API answer enables the image: preview_url is the API thumbnail verbatim, rights CLEARED with its basis, attribution derived from the API", () => { const r = gRun(resolver.CACHE_DIR), a = r.norm.record.media[0]; ok(r.validation.ok && a.preview_url === ii(realResp).thumburl && a.display_mode === "image" && a.rights.status === "CLEARED" && a.rights.display_clearance === true, "applied"); ok(/^https:\/\/thumb\.wikimedia\.org\/wikipedia\/commons\/thumb\//.test(a.preview_url) && a.resolution.api_license_code === "CC0-1.0" && a.resolution.api_creator === "Aaadir" && a.attribution_derived === 'Aaadir, “תל הרור1.jpg,” Wikimedia Commons, CC0.', "derived fields"); ok(a.attribution.indexOf("Aaadir") >= 0, "note attribution kept"); return [a.preview_url.slice(0, 90) + "…"]; });
held("R02", "file missing in the API answer → attribution-only", (r) => { r.query.pages = [{ title: "File:תל הרור1.jpg", missing: true }]; }, /not found/);
held("R03", "API license differs from the research license → no preview", (r) => { ii(r).extmetadata.LicenseShortName.value = "CC BY-SA 4.0"; }, /license/);
held("R04", "API creator differs from the research creator → no preview", (r) => { ii(r).extmetadata.Artist.value = '<a href="//commons.wikimedia.org/wiki/User:Someone">Someone Else</a>'; }, /creator/);
held("R05", "thumbnail on a foreign host → rejected", (r) => { ii(r).thumburl = "https://evil.example/thumb/a.jpg"; }, /thumbnail URL/);
held("R06", "API title differs from the research file title → rejected", (r) => { pg(r).title = "File:Other.jpg"; }, /title/);
held("R07", "API description page differs from the research source_url → rejected", (r) => { ii(r).descriptionurl = "https://commons.wikimedia.org/wiki/File:Other.jpg"; }, /description page/);
held("R08", "non-raster mime type (svg) → rejected", (r) => { ii(r).mime = "image/svg+xml"; }, /mime/);
held("R09", "API lists restrictions → rejected", (r) => { ii(r).extmetadata.Restrictions = { value: "trademarked" }; }, /restrictions/);
t("R10", "a verified API answer never clears a record whose declared rights status is not clearable (free text / VERIFY / missing)", () => { const d = fs.mkdtempSync(path.join(os.tmpdir(), "jbc-rs-")), f = path.join(d, path.basename(GERAR)); fs.writeFileSync(f, gsrc.replace(/rights_status: PUBLIC_DOMAIN_DEDICATION_CC0/g, "rights_status: reusable with attribution")); const r = gRun(resolver.CACHE_DIR, { source: f }), a = r.norm.record.media[0]; ok(r.validation.ok && a.resolution.verified === true && a.resolution.eligible_for_display === false && a.preview_url === null && a.rights.status !== "CLEARED", "must not clear: " + JSON.stringify(a.resolution.reasons)); ok(/not one that clears display/.test(a.resolution.reasons.join()), "reason"); return [a.resolution.reasons.join(" | ").slice(0, 140)]; });
t("R11", "offline by default: no cache → unresolved, attribution-only, record still valid; an asset without a verified source page is never touched by the resolver", () => { const r = gRun(fs.mkdtempSync(path.join(os.tmpdir(), "jbc-empty-"))); ok(r.validation.ok && r.norm.record.media.every((a) => a.preview_url === null && a.display_mode === "attribution_only" && a.resolution.verified === false && a.resolution.source === "none"), "unresolved"); const nourl = withOverlay((o) => { Object.values(o.media_bindings).forEach((b) => { delete b.source_url; }); }), b = run({ krv, overlay: nourl, syncFile: path.join(tmp, "x.json"), cacheDir: resolver.CACHE_DIR }); ok(b.norm.record.media.every((a) => a.resolution === undefined && a.preview_url === null && a.source_url === null), "no verified URL → no resolution object"); return ["no cache → attribution-only"]; });
t("R12", "an injected resolver failure mode: a corrupt cache file is treated as no cache", () => { const d = fs.mkdtempSync(path.join(os.tmpdir(), "jbc-bad-")); fs.writeFileSync(resolver.cacheFile(d, "File:תל הרור1.jpg"), "{not json"); const r = gRun(d), a = r.norm.record.media[0]; ok(r.validation.ok && a.preview_url === null && a.resolution.source === "none", "corrupt cache"); return ["corrupt cache ignored"]; });
t("R13", "incremental: the same cache twice is unchanged; a changed API answer changes only that asset's hash", () => { const c1 = cacheWith(noEd, noEd), a = gRun(c1), sf = path.join(tmp, "inc-sync.json"); fs.writeFileSync(sf, JSON.stringify({ records: { "JBC-CR-PLACE-GERAR-001": Object.fromEntries(a.norm.record.media.map((m) => [m.id, m.content_hash])) } })); const same = gRun(c1, { syncFile: sf }).sync; ok(same.unchanged.length === 2 && !same.changed.length, JSON.stringify(same)); const c2 = cacheWith((r) => { ii(r).extmetadata.Restrictions = { value: "x" }; }, noEd), ch = gRun(c2, { syncFile: sf }).sync; ok(ch.changed.join() === "JBC-MEDIA-GR-001" && ch.unchanged.join() === "JBC-MEDIA-GR-002", JSON.stringify(ch)); const c3 = cacheWith(noEd, noEd), t1 = JSON.parse(fs.readFileSync(resolver.cacheFile(c3, "File:תל הרור1.jpg"), "utf8")); t1.retrieved_at = "2030-01-01T00:00:00.000Z"; fs.writeFileSync(resolver.cacheFile(c3, "File:תל הרור1.jpg"), JSON.stringify(t1)); ok(gRun(c3, { syncFile: sf }).sync.unchanged.length === 2, "retrieval time alone must not change the hash"); return ["unchanged", "changed=" + ch.changed]; });
ta("R14", "refreshCache: queries only assets with a verified explicit source page, writes the API answer verbatim, never overwrites the cache when a request fails", async () => {
  const calls = [], d = fs.mkdtempSync(path.join(os.tmpdir(), "jbc-rf-")), fake = async (url) => { calls.push(url); return clone(realResp); };
  const nourl = clone(rec); nourl.media.forEach((a) => { a.source_url = null; a.source_url_verified = false; }); const bsr = await resolver.refreshCache(nourl, { fetcher: fake, cacheDir: d }); ok(calls.length === 0 && bsr.every((x) => /^skipped/.test(x.status)), "assets without a verified source page must not be queried: calls=" + calls.length);
  const gr = await resolver.refreshCache(G, { fetcher: fake, cacheDir: d }); ok(calls.length === 2 && gr.every((x) => x.status === "fetched") && calls.every((u) => u.indexOf("https://commons.wikimedia.org/w/api.php?") === 0 && /titles=/.test(u)), "two queries to the official API only: " + calls.length);
  const before = fs.readFileSync(resolver.cacheFile(d, "File:תל הרור1.jpg"), "utf8"), bad = await resolver.refreshCache(G, { fetcher: async () => { throw new Error("network down"); }, cacheDir: d }); ok(bad.every((x) => /^failed/.test(x.status)) && fs.readFileSync(resolver.cacheFile(d, "File:תל הרור1.jpg"), "utf8") === before, "a failed request must not overwrite the cache"); return ["queries=" + calls.length];
});
t("R15", "the pipeline never downloads media: no image bytes in the projection, no cache file holds image data, only API JSON", () => { const files = fs.readdirSync(resolver.CACHE_DIR); ok(files.length >= 2 && files.every((f) => /\.json$/.test(f)), "cache files are json"); for (const f of files) { const t0 = fs.readFileSync(path.join(resolver.CACHE_DIR, f), "utf8"); ok(!/data:image|base64,/.test(t0) && t0.length < 20000, "cache entry is API metadata only: " + f); } ok(gres.mediaReport.image_payloads === 0 && gres.mediaReport.invented_preview_urls === 0, "report"); return ["cache files=" + files.length]; });

// ---- generic spatial binding (research projection → Map) ----
const numIn = (text, n) => new RegExp("(^|[^\\d.])" + String(n).replace(".", "\\.") + "0*(?![\\d])").test(text);
const spatialBlocks = () => { const blk = (f, a, b) => { const t0 = fs.readFileSync(f, "utf8"), i = t0.indexOf(a), j = t0.indexOf(b, i); return i >= 0 && j > i ? t0.slice(i, j) : ""; }; return { normalize: blk(path.join(__dirname, "normalize.js"), "<spatial-binding>", "</spatial-binding>") + blk(path.join(__dirname, "normalize.js"), "function siteMarker", "function normalize(parsed"), validate: blk(path.join(__dirname, "validate.js"), "V36: spatial read model", "approval + identity expectations"), app: blk(path.join(ROOT, "app.js"), "<spatial-binding>", "</spatial-binding>") }; };
t("S01", "one generic spatial read model for every record (same schema, same keys, produced by the same code)", () => { ok(BS.spatial && G.spatial && BS.spatial.schema === "JBC_SPATIAL_READ_MODEL_v0.1" && G.spatial.schema === BS.spatial.schema, "schema"); ok(Object.keys(BS.spatial).join() === Object.keys(G.spatial).join(), "same keys: " + Object.keys(BS.spatial)); ok(BS.spatial.subject.stable_id === BS.stable_id && G.spatial.subject.stable_id === G.stable_id && BS.spatial.subject.kind === "Place", "spatial identity = the research stable_id"); return ["keys=" + Object.keys(G.spatial).join(",")]; });
t("S02", "coordinates only as supplied: every spatial coordinate literally appears in its note; none computed for anything else", () => { for (const [R, txt] of [[BS, srcText], [G, gsrc]]) { for (const x of R.spatial.sites) if (x.lat !== null) ok(numIn(txt, x.lat) && numIn(txt, x.lon), "coordinate not in the note: " + x.label + " " + x.lat + "," + x.lon); ok(R.spatial.primary.coordinates === null, R.stable_id + ": no primary coordinate was produced"); } ok(G.spatial.sites.filter((x) => x.lat === null).length === 1 && G.spatial.sites.find((x) => x.lat === null).label === "Tell el-Far'a South", "a site without a coordinate stays without one"); return ["sites with coordinates: BS=" + BS.spatial.sites.length + " G=" + G.spatial.sites.filter((x) => x.lat !== null).length]; });
t("S03", "status preserved, marker rule applied, no fake exact pin: Beersheba draws its two recognized sites only; Gerar (no status stated) draws nothing", () => {
  ok(BS.spatial.sites.map((x) => x.coordinate_status + "=" + x.marker.style).join() === "VERIFIED_ARCHAEOLOGICAL_SITE=site,MODERN_CITY_REFERENCE=modern" && BS.spatial.degradation.markers === 2, "Beersheba: " + JSON.stringify(BS.spatial.sites.map((x) => x.marker)));
  ok(G.spatial.sites.every((x) => x.coordinate_status === null && x.marker.render === false) && G.spatial.degradation.markers === 0 && G.spatial.degradation.reason === "coordinates_present_but_status_not_drawable", "Gerar: no invented status, no marker, reason stated"); for (const R of [BS, G]) ok(R.spatial.primary.marker.render === false && R.spatial.primary.marker.reason === "no_exact_coordinate" && R.spatial.primary.exact_marker === false && R.spatial.primary.coordinate_status === R.coordinate_status, R.stable_id + ": primary place is never drawn"); return ["BS markers=2", "Gerar markers=0 (" + G.spatial.degradation.reason + ")"];
});
t("S04", "Place / Region / Route / Site separation: a region has no point or boundary, routes have no geometry, none is mixed into sites", () => {
  for (const R of [BS, G]) { const sp = R.spatial; ok(sp.region.boundary === null && !("lat" in sp.region) && !("lon" in sp.region) && !("geometry" in sp.region), R.stable_id + ": region"); ok(sp.routes.length > 0 && sp.routes.every((r) => r.geometry === null && r.geometry_status === "NOT_ASSIGNED"), R.stable_id + ": routes"); ok(!sp.sites.some((x) => sp.routes.some((r) => r.label === x.label) || x.label === sp.region.label), R.stable_id + ": sites are only sites"); }
  ok(BS.spatial.region.stable_ref === "JBC-CR-REGION-BEERSHEBA_VALLEY-001" && G.spatial.region.stable_ref === null, "region identity as written (none invented for Gerar)"); return ["BS routes=" + BS.spatial.routes.length, "G routes=" + G.spatial.routes.length];
});
t("S05", "certainty dimensions stay separate and unchanged: identity vs coordinate vs per-site identification", () => {
  for (const R of [BS, G]) ok(R.spatial.certainty.identity === R.certainty && R.spatial.certainty.coordinate === R.coordinate_certainty && R.spatial.certainty.identity !== R.spatial.certainty.coordinate, R.stable_id + ": " + JSON.stringify(R.spatial.certainty));
  ok(G.spatial.sites.map((x) => x.identification_certainty).join() === "MEDIUM,LOW_DISPUTED,LOW,LOW" && G.spatial.sites.every((x) => x.equivalence_locked === false), "per-site identification certainty kept apart and never equated"); return [JSON.stringify(G.spatial.certainty)];
});
t("S06", "VERIFY / HOLD preserved through the spatial model", () => { for (const R of [BS, G]) ok(JSON.stringify(R.spatial.verify_hold) === JSON.stringify({ verify: R.verify.map((v) => v.id), hold: R.hold.length }) && R.verify.length > 0, R.stable_id); return ["BS verify=" + BS.verify.length, "G verify=" + G.verify.length + " hold=" + G.hold.length]; });
t("S07", "no-coordinate graceful degradation: a note without any map block/candidates still validates with an empty spatial model and a stated reason; a corrupted coordinate fails closed (never clamped or guessed)", () => {
  const nm = gerarOnly((t0) => t0.replace("map_ready:", "map_ready_x:")); ok(nm.validation.ok, JSON.stringify(nm.validation.errors)); const sp = nm.norm.record.spatial; ok(sp.sites.length === 0 && sp.degradation.markers === 0 && sp.degradation.reason === "no_coordinates_supplied" && sp.primary.coordinates === null && sp.primary.marker.render === false, "empty model: " + JSON.stringify(sp.degradation));
  const bad = gerarOnly((t0) => t0.split("lat: 31.382100").join("lat: 931.382100")); ok(!bad.validation.ok && bad.validation.errors.some((e) => /V26/.test(e)), "corrupted coordinate must be rejected: " + JSON.stringify(bad.validation.errors)); return ["no map block → degradation=" + sp.degradation.reason, "corrupt lat → V26"];
});
t("S08", "no record-specific branch: the spatial code (normalize, validate, app) names no record, place or site", () => { const b = spatialBlocks(); for (const k of Object.keys(b)) { ok(b[k].length > 200, k + ": block found"); ok(!/beersheba|gerar|브엘세바|그랄|haror|tel be|\bJBC-CR-/i.test(b[k].replace(/"JBC-CR-"|\^JBC-CR-/g, "")), k + ": names a specific record"); } return ["blocks=" + Object.keys(b).join(",")]; });

// ---- stale-source guard (JBC_VAULT missing must never silently fall back to the repo mirror on a real write run)
const cpx = require("child_process"), RUN = path.join(__dirname, "run.js"), realFiles = () => [dataFile, idxFile].map(sha).join();
const guardRun = (args, env) => cpx.spawnSync(process.execPath, [RUN].concat(args), { env: env, encoding: "utf8" });
const noVaultEnv = Object.assign({}, process.env); delete noVaultEnv.JBC_VAULT;
t("G01", "write run without JBC_VAULT is refused (exit 3, STALE_SOURCE_GUARD) and writes nothing", () => { const b = realFiles(), r = guardRun([], noVaultEnv); ok(r.status === 3 && /STALE_SOURCE_GUARD: JBC_VAULT is not bound/.test(r.stderr), r.status + " " + r.stderr); ok(realFiles() === b, "real projection/index must be untouched"); });
t("G02", "--allow-mirror still cannot change the recorded source lineage (needs --accept-source-change)", () => { const prevSha = base.norm.record.source_refs[0].sha256, projTxt = fs.readFileSync(dataFile, "utf8"); if (projTxt.indexOf(prevSha) >= 0) { /* projection already reproduces the mirror — nothing to refuse */ return ["mirror sha equals the projected sha"]; } const b = realFiles(), r = guardRun(["--allow-mirror"], noVaultEnv); ok(r.status === 3 && /would change the recorded source lineage/.test(r.stderr), r.status + " " + r.stderr); ok(realFiles() === b, "untouched"); });
t("G03", "a bound but unavailable vault fails loudly (never falls back)", () => { const r = guardRun(["--dry"], Object.assign({}, process.env, { JBC_VAULT: path.join(os.tmpdir(), "jbc-no-such-vault") })); ok(r.status === 1 && /JBC_VAULT is bound but unavailable/.test(r.stderr), r.status + " " + r.stderr); });
t("G04", "dry runs and temp-dir ingests stay unguarded (tests/tools can still use the mirror explicitly)", () => { const r = guardRun(["--dry"], noVaultEnv); ok(r.status === 0 && /"wrote": false/.test(r.stdout), r.status + " " + r.stderr); });

const out = path.join(__dirname, "out"); fs.mkdirSync(out, { recursive: true });
Promise.all(pending).then(() => {
const summary = { total: results.length, passed: results.filter((r) => r.pass).length, verdict: results.every((r) => r.pass) ? "PASS" : "FAIL", results };
fs.writeFileSync(path.join(out, "test-results.json"), JSON.stringify(summary, null, 2));
console.log(summary.verdict + " " + summary.passed + "/" + summary.total); if (!process.env.JBC_VAULT) console.log("NOTE: JBC_VAULT is not bound — mirror-dependent checks (P08, N12, N19, N41, M*, I01) are EXPECTED to fail while the repo mirror is stale; bind the vault to run the authoritative suite."); results.filter((r) => !r.pass).forEach((r) => console.log("FAIL " + r.id + " " + r.name + " — " + r.error));
process.exit(summary.verdict === "PASS" ? 0 : 1);
});
