"use strict";
// Region-specific validation (fail-closed). The Place validator (validate.js) is not touched or relaxed; regions never pass through it.
function validateRegion(rec, ctx) {
  ctx = ctx || {}; const errors = [], warnings = [], checks = [], check = (id, ok, msg, level) => { checks.push({ id, ok: !!ok, msg }); if (!ok) (level === "warn" ? warnings : errors).push(id + ": " + msg); };
  if (!rec) { errors.push("no record"); return { ok: false, errors, warnings, checks }; }
  const krv = ctx.krv, B = rec.identity_binding || {};
  check("R01_entity_type", rec.entity_type === "Region", "entity_type must be Region (no region→place coercion)");
  check("R02_viewer_id", /^JBC-CR-[A-Z]+-[A-Z0-9_]+-\d{3}$/.test(rec.stable_id || "") && (!ctx.expected_identity || rec.stable_id === ctx.expected_identity), "viewer stable_id must be an explicit JBC-CR id equal to the configured identity: " + rec.stable_id);
  check("R03_binding", B.viewer_stable_id === rec.stable_id && B.binding_role === "VIEWER_BINDING_ID_ONLY" && B.equivalence_semantics === "NOT_AUTOMATIC_CROSSWALK" && B.BAT01_PLACE_reuse === false && B.BAT01_P_crosswalk === false && B.automatic_merge === false, "identity binding must be viewer-only, NOT_AUTOMATIC_CROSSWALK, no reuse / crosswalk / merge");
  check("R04_registry_reference_only", !!B.source_registry_id && B.source_registry_id !== rec.stable_id && B.source_registry_id === rec.declared.registry_stable_id && B.source_registry_id_role === "REFERENCE_ONLY", "registry id is carried as reference only and never as the record id");
  // profile "worbs_sections": the note states no BAT01_P prefix conversion, so only the attested mutation facts are required (all NONE) and the BAT01_REG crosswalk must read NOT_INFERRED
  const sections = ctx.profile === "worbs_sections", needMut = sections ? ["Registry", "new_PLACE_ID", "geometry_creation", "polygon_creation", "route_polyline_creation"] : ["Registry", "new_PLACE_ID", "BAT01_P_prefix_conversion", "geometry_creation", "polygon_creation", "route_polyline_creation"];
  check("R05_no_registry_mutation", rec.authority.registry_effect === "NONE" && rec.authority.BAT01_crosswalk === "NOT_PERFORMED" && rec.declared.mutation && needMut.every((k) => rec.declared.mutation[k] === "NONE") && (!sections || rec.declared.BAT01_REG_crosswalk === "NOT_INFERRED"), "note's mutation facts must be all NONE" + (sections ? " and the BAT01_REG crosswalk NOT_INFERRED" : ""));
  const sr = rec.source_refs && rec.source_refs[0];
  check("R06_source_lineage", !!(sr && sr.id && sr.sha256 && (sections ? !sr.predecessor_sha256 || sr.sha256 !== sr.predecessor_sha256 : sr.predecessor_sha256 && sr.change_scope === "CONTROL_METADATA_ONLY" && sr.sha256 !== sr.predecessor_sha256)), sections ? "source id + sha256 (the note declares no predecessor; none is invented)" : "source id + sha256 + declared predecessor, change scope CONTROL_METADATA_ONLY");
  const keys = []; (function w(o, p) { if (o && typeof o === "object") Object.keys(o).forEach((k) => { if (/^(lat|lon|lng|latitude|longitude)$/i.test(k) || ((k === "coordinates" || k === "centroid") && o[k] !== null)) keys.push(p + "." + k); w(o[k], p + "." + k); }); })(rec, "");
  const sp = rec.spatial || {}, d = sp.declared || {};
  check("R07_no_coordinate", rec.coordinates === null && rec.centroid === null && sp.primary && sp.primary.coordinates === null && !keys.length && d.exact_coordinate_value === "NONE" && d.centroid_value === "NONE", "no coordinate / centroid / lat-lon key (found: " + keys.join(",") + ")");
  const pt = sp.reference_only && sp.reference_only.external_representative_point;
  check("R08_reference_point_unpromoted", !pt || (pt.promote_to_record_coordinate === false && pt.coordinates_embedded === false && pt.rendered === false), "an external representative point may not be promoted or embedded");
  check("R09_no_marker_polygon_route", sp.primary && sp.primary.marker.render === false && !(sp.sites || []).length && sp.region && sp.region.boundary === null && sp.region.render === "HOLD" && !(sp.routes || []).length && d.exact_polygon_value === "NONE" && !(sp.reference_only && sp.reference_only.external_geometry && (sp.reference_only.external_geometry.rendered || sp.reference_only.external_geometry.geometry_embedded)), "no marker, polygon, embedded geometry or route; region render HOLD");
  check("R10_reader_unpublished", rec.reader && rec.reader.published === false && rec.media && rec.media.bound === false && (rec.media.references || []).every((m) => m.preview_url === null && m.display_mode === "attribution_only" && !m.image_url && !m.payload && !m.data), "reader layer and media are not published for regions (media references are metadata only: no preview URL / payload, attribution_only)");
  const withVerify = /WITH_VERIFY/.test(rec.status || "");
  check("R11_verify_hold", rec.verify.length === (ctx.sourceVerifyCount != null ? ctx.sourceVerifyCount : rec.verify.length) && (!withVerify || rec.verify.length > 0) && rec.verify.every((v) => v.id && v.issue) && rec.hold.length === (ctx.sourceHoldCount != null ? ctx.sourceHoldCount : rec.hold.length) && JSON.stringify(sp.verify_hold) === JSON.stringify({ verify: rec.verify.map((v) => v.id), hold: rec.hold.length }), "VERIFY/HOLD preserved exactly as written (status keeps WITH_VERIFY)");
  const bad = [], direct = (rec.passage_links || []).filter((l) => l.group === "direct");
  if (krv) (rec.passage_links || []).forEach((l) => { const b = l.book && krv.books.find((x) => x.id === l.book), ch = b && b.chapters[l.chapter - 1]; if (!l.book || !ch || (l.v1 && (l.v1 > ch.length || (l.v2 && l.v2 > ch.length)))) bad.push(l.raw); });
  check("R12_passages", direct.length > 0 && direct.length === rec.declared.direct_ref_count && direct.every((l) => l.source === "S066") && !bad.length, "direct set = declared count and every ref exists in KRV (unresolved: " + bad.join(",") + ")");
  check("R13_claims", (rec.claims || []).length > 0 && rec.claims.every((c) => c.id && c.statement && c.locator && c.confidence) && new Set(rec.claims.map((c) => c.id)).size === rec.claims.length, "claims complete with unique ids");
  check("R14_unresolved_relations", (rec.relations || []).every((r) => r.resolved === false && r.to_id === null) && (rec.related_people || []).every((p) => p.resolved === false) && (rec.related_events || []).every((e) => e.resolved === false), "relations are never resolved by name");
  const au = rec.authority || {};
  check("R15_approval_authority", /^CAPTAIN_APPROVED$|APPROVED/.test(au.approval || "") && !!au.approval_source && au.approval_origin === "ingest_authority" && !!au.note_approval_status && !!au.approval_record_id && au.approval_scope === "IDENTITY_BINDING_ONLY" && !!au.approval_recorded_at, "approval must come from a durable approval record (id, scope IDENTITY_BINDING_ONLY, recorded_at; value + source recorded, the note's own value kept as note_approval_status) — equivalent of Place V33; effective approval: " + au.approval);
  check("R16_no_publication", rec.activation && rec.activation.publishable === false && ["ISOLATED_DRY_RUN_ONLY", "NOT_ACTIVATED"].includes(rec.activation.state), "approval never publishes: never publishable; state is ISOLATED_DRY_RUN_ONLY (dry run) or NOT_ACTIVATED (canonical file carries the region but nothing consumes or activates it)");
  const g = rec.geometry || {};
  check("R17_geometry_contract", g.status === "none" ? (g.type === null && g.approved === false && g.approximate_area === null && g.map_polygon === "OMIT" && g.detail === "AVAILABLE" && g.relations === "AVAILABLE") : (["polygon", "multipolygon", "approximate_area"].includes(g.type) && g.approved === true && !!g.approval_source), "geometry: none is allowed (polygon omitted, detail + relations available); polygon / multipolygon / approximate_area only with explicit approved geometry and its approval source");
  return { ok: errors.length === 0, errors, warnings, checks };
}
module.exports = { validateRegion };
